# -*- coding: utf-8 -*-
"""
HSK 7-9 Grammar - Part 1A: Items 001 - 014 (119 sentences)
Hình vị cấu từ, Từ loại chuyên biệt, Đại từ, Lượng từ, Phó từ mức độ, phạm vi, thời gian, tần suất.
"""

METADATA_1A = [
    {
        "order": 1,
        "titleVi": "Tiền tố cấu từ cao cấp: 后— (hậu-), 亲— (thân-)",
        "structure": "后 / 亲 + Danh từ / Động từ",
        "category": "cau-tu-tu-loai",
        "explanation": "Hai tiền tố cao cấp trong HSK 7-9: 1) '后—' (hậu-) biểu thị giai đoạn hoặc thời kỳ sau một sự kiện, trào lưu hoặc sự cố lớn (后奥运时代 - thời kỳ hậu Olympic, 后疫情时代 - thời kỳ hậu đại dịch, 后现代 - hậu hiện đại); 2) '亲—' (thân-) biểu thị tự tay mình, trực tiếp có mặt làm hành động thể hiện tình cảm, sự gần gũi hoặc trách nhiệm cao (亲手 - đích thân ra tay, 亲眼 - tận mắt, 亲笔 - đích thân chấp bút, 亲历 - trực tiếp trải qua).",
        "tips": "Thường gặp trong các văn bản thời sự, kinh tế và chính trị để chỉ bối cảnh chuyển tiếp hoặc hành động trực tiếp của lãnh đạo."
    },
    {
        "order": 2,
        "titleVi": "Các hậu tố định danh & tính chất chuyên ngành: —观, —鬼, —界, —然, —坛, —为, —制",
        "structure": "Từ căn + 观 / 鬼 / 界 / 然 / 坛 / 为 / 制",
        "category": "cau-tu-tu-loai",
        "explanation": "Bảy hậu tố định danh trình độ cao: 1) '—观': quan niệm, nhân sinh quan (价值观 - giá trị quan, 消费观, 审美观); 2) '—鬼': kẻ có tính cách/thói quen xấu đặc trưng (小气鬼 - kẻ bủn xỉn, 捣蛋鬼, 贪吃鬼); 3) '—界': giới, lĩnh vực hoạt động (学术界 - giới học thuật, 产业界, 演艺界); 4) '—然': hậu tố tính từ/phó từ cổ biểu thị trạng thái (安然 - bình an yên ổn, 偶然, 坦然); 5) '—坛': vũ đài, diễn đàn nghệ thuật/thể thao (体坛 - làng thể thao, 文坛, 乐坛); 6) '—为': được coi là, được tán thành rộng rãi (广为 - được rộng rãi...: 广为称赞, 广为流传); 7) '—制': chế độ, hệ thống tổ chức (公有制 - chế độ công hữu, 会员制, 责任制).",
        "tips": "Nắm vững các hậu tố này là chìa khóa đọc hiểu nhanh các thuật ngữ trừu tượng trong văn bản học thuật và báo chí chính luận HSK 7-9."
    },
    {
        "order": 3,
        "titleVi": "Chùm từ loại chính luận đặc biệt: 巴不得, 并非, 除外, 犯不着, 犯得着, 恨不得, 可否, 可谓, 免不了, 所谓, 有所, 予以",
        "structure": "Từ loại chính luận / thành ngữ ngữ pháp + Vị ngữ",
        "category": "cau-tu-tu-loai",
        "explanation": "Nhóm từ vựng - ngữ pháp cao cấp có tần suất xuất hiện cực cao: '巴不得' / '恨不得' (chỉ mong sao, thèm muốn tột cùng); '并非' (tuyệt nhiên không phải là - phủ định dứt khoát); '除外' (ngoại trừ... ra); '犯不着' / '犯得着' (không đáng / có đáng hay không - biểu thị sự cân nhắc thiệt hơn); '可否' (có thể được chăng - thỉnh thị ý kiến trang trọng); '可谓' (quả thực có thể gọi là); '免不了' (khó tránh khỏi); '所谓' (cái gọi là); '有所' (có phần, có sự... - 有所提高, 有所顾虑); '予以' (tiến hành, dành cho... - 予以批评, 予以支持).",
        "tips": "Đây là cốt lõi của văn phong công văn, xã luận và tranh biện tri thức trong kỳ thi HSK 7-9."
    },
    {
        "order": 4,
        "titleVi": "Đại từ nhân xưng sở hữu thể chế: 我 (Tôi / Bên chúng tôi, trường chúng tôi)",
        "structure": "我 + Cơ quan / Tổ chức / Trường học (我校 / 我司 / 我国 / 我部)",
        "category": "cau-tu-tu-loai",
        "explanation": "Trong văn bản công văn, phát biểu chính thức hoặc thư tín thương mại, '我' không chỉ là đại từ nhân xưng ngôi thứ nhất cá nhân mà được dùng làm tiền tố đại diện cho cả tập thể, tổ chức của mình (我校 - trường chúng tôi; 我公司 / 我司 - công ty chúng tôi; 我国 - đất nước chúng tôi).",
        "tips": "Mang sắc thái trang trọng, tự hào và chuẩn mực ngoại giao công sở."
    },
    {
        "order": 5,
        "titleVi": "Đại từ chỉ thị văn ngôn & công văn: 彼 (bỉ - kia/người kia), 这么着 (thế này), 兹 (tư - nay/đây)",
        "structure": "彼 / 这么着 / 兹 + Danh từ / Vị ngữ",
        "category": "cau-tu-tu-loai",
        "explanation": "'彼' (bǐ) chỉ đối phương hoặc thời điểm xa xưa ('彼时' - lúc ấy, thời ấy; '此...非彼...' - cái này không phải cái kia; '知己知彼' - biết mình biết người); '这么着' (zhèmezhe) là khẩu ngữ: 'làm như thế này, thế này đi'; '兹' (zī) là từ mở đầu công văn thông cáo pháp lý: 'nay, nay có' ('兹证明' - nay chứng nhận rằng; '兹有' - nay có).",
        "tips": "'兹证明' là câu mở đầu bất hủ trong mọi loại giấy chứng nhận công tác, chứng nhận cư trú văn bản tiếng Trung."
    },
    {
        "order": 6,
        "titleVi": "Đại từ nghi vấn văn ngôn & khẩu ngữ: 何 (hà - cái gì/ở đâu/sao), 怎么着 (thế nào/ra sao)",
        "structure": "何 + Danh từ / Động từ  ||  怎么着 (cuối câu / làm vị ngữ)",
        "category": "cau-tu-tu-loai",
        "explanation": "'何' (hé) là đại từ nghi vấn gốc Hán cổ tương đương 什么, 为什么, 哪里 ('何时' - khi nào, '何地' - nơi đâu, '何在' - ở chỗ nào, '因何' - vì sao); '怎么着' (zěnmezhe) là đại từ nghi vấn khẩu ngữ dùng để hỏi cách xử lý hoặc phỏng đoán tình huống mơ hồ (làm sao đây / hay là ra sao).",
        "tips": "'何' thường dùng tạo câu hỏi tu từ đầy sức gợi cảm trong văn chương nghị luận."
    },
    {
        "order": 7,
        "titleVi": "Đại từ số lượng ước đoán: 若干 (ruògān - một số, vài, đôi ba)",
        "structure": "若干 + Lượng từ / Danh từ  ||  Danh từ + 若干",
        "category": "cau-tu-tu-loai",
        "explanation": "'若干' là đại từ số lượng không xác định mang màu sắc văn viết trang trọng, biểu thị một số lượng nhất định (nhiều hơn một) hoặc dùng trong câu hỏi khảo sát thống kê.",
        "tips": "Có thể đứng trước danh từ (若干优秀歌手) hoặc đứng sau danh từ trong danh mục liệt kê (随笔若干)."
    },
    {
        "order": 8,
        "titleVi": "Hệ thống lượng từ danh từ chuyên biệt HSK 7-9: 重, 截, 缕, 码, 枚, 摊, 丸, 则, 幢, 宗",
        "structure": "Số từ + Lượng từ chuyên dụng + Danh từ",
        "category": "cau-tu-tu-loai",
        "explanation": "Các lượng từ tinh tế: 1) '重' (chóng): lớp, tầng mâu thuẫn/khó khăn (多重原因, 重重困难); 2) '截' (jié): khúc, đoạn (一截木头, 凉了半截); 3) '缕' (lǚ): lọn tóc, luồng hương/khói (一缕秀发, 缕缕清香); 4) '码' (mǎ): chuyện, sự vụ (两码事, 一码归一码); 5) '枚' (méi): huân chương, đồng xu, con dấu (一枚硬币, 五枚奖章); 6) '摊' (tān): đống việc bừa bộn (一摊事); 7) '丸' (wán): viên hoàn thuốc đông y (一丸药, 每次六丸); 8) '则' (zé): mẩu tin tức, câu chuyện ngụ ngôn/điển cố (一则新闻, 20则典故); 9) '幢' (zhuàng): tòa nhà, dãy nhà (一幢教学楼, 宿舍三幢); 10) '宗' (zōng): vụ án, mối làm ăn lớn (一宗案件, 一宗生意).",
        "tips": "Thành ngữ '一码归一码' (chuyện nào ra chuyện đó) là cụm từ vàng trong giao tiếp công việc."
    },
    {
        "order": 9,
        "titleVi": "Động lượng từ khẩu ngữ trách móc: 通 (tòng - một hồi, một chập)",
        "structure": "Động từ (批评 / 训 / 骂) + 一通 / 好一通",
        "category": "cau-tu-tu-loai",
        "explanation": "'通' (thanh 4: tòng) làm động lượng từ diễn tả hành động kéo dài liên tục suốt một khoảng thời gian, thường dùng với các động từ mắng mỏ, phê bình hoặc thuyết giáo (好一通批评 - phê bình cho một hồi; 训了一通 - mắng cho một trận).",
        "tips": "Thường đi kèm phó từ '好一通' hoặc '狠狠...了一通' để nhấn mạnh mức độ gay gắt."
    },
    {
        "order": 10,
        "titleVi": "Lượng từ phức hợp thống kê: 人次 (réncì - lượt người)",
        "structure": "Số lượng + 人次",
        "category": "cau-tu-tu-loai",
        "explanation": "'人次' là lượng từ phức hợp kết hợp giữa 'người' (nhân) và 'lượt' (thứ), dùng trong báo cáo số liệu kinh tế, du lịch, thư viện để tính tổng số lượt người tham gia (dù một người có thể tham gia nhiều lần).",
        "tips": "Rất phổ biến trong biểu đồ và đề thi viết luận phân tích dữ liệu thống kê HSK 7-9."
    },
    {
        "order": 11,
        "titleVi": "Chùm phó từ mức độ văn ngôn & nghị luận: 大为, 分外, 何等, 极度, 极力, 略, 略微, 颇, 稍稍, 万分, 微, 尤为, 愈加, 越发",
        "structure": "Phó từ mức độ + Tính từ / Động từ tâm lý",
        "category": "cau-tu-tu-loai",
        "explanation": "Hệ thống phó từ sắc thái biểu cảm cao cấp: '大为' (hết sức, rất đỗi - 大为惊叹, 大为不满); '分外' (đặc biệt khác thường - 分外小心, 分外高大); '何等' (biết bao, dường nào - 何等幸运); '极度' (cực độ - 极度紧张); '极力' (hết sức ra sức - 极力反对); '略' / '略微' (hơi, đôi chút - 略高于, 略知一二); '颇' (khá là, rất - 颇感兴趣, 颇受青睐); '稍稍' (hơi chút, tạm chút - 稍稍歇息); '万分' (muôn phần, vô vàn - 万分感激, 激动万分); '微' (hơi, he hé - 面色微红, 微张着嘴); '尤为' (càng thêm đặc biệt - 尤为突出, 尤为引人注目); '愈加' / '越发' (càng ngày càng - 愈加成熟, 越发强烈).",
        "tips": "Là kho vũ khí từ vựng cốt lõi giúp bài văn HSK 7-9 đạt chuẩn mực hành văn học thuật xuất sắc."
    },
    {
        "order": 12,
        "titleVi": "Chùm phó từ phạm vi bao quát & loại trừ: 大体, 概, 皆, 尽, 均, 通通, 统统, 唯, 唯独, 唯有, 无非, 一概",
        "structure": "Chủ ngữ + Phó từ phạm vi + Vị ngữ",
        "category": "cau-tu-tu-loai",
        "explanation": "Các phó từ phạm vi văn ngôn và pháp lý: '大体' (đại thể, nhìn chung); '概' / '一概' (tất cả, hoàn toàn không phân biệt - 一概不知, 一概作废); '皆' / '均' (đều là, đều - 皆大欢喜, 均有所提高); '尽' (toàn bộ, hết thảy - 尽显, 尽是); '通通' / '统统' (tuốt tuồn tuột, toàn bộ - khẩu ngữ và văn viết); '唯' / '唯独' / '唯有' (chỉ có duy nhất, riêng chỉ có - 唯独他没来, 唯有一试); '无非' (chẳng qua chỉ là - 无非是为了).",
        "tips": "'皆', '均' thay cho '都' trong văn chính luận tạo giọng điệu trang trọng, đĩnh đạc."
    },
    {
        "order": 13,
        "titleVi": "Chùm phó từ thời gian văn bản & pháp lý: 姑且, 即, 即时, 届时, 尽早, 就此, 历来, 尚, 随即, 向来, 一经, 暂且, 早日",
        "structure": "Phó từ thời gian + Động từ",
        "category": "cau-tu-tu-loai",
        "explanation": "Chỉ nhịp điệu và tiến trình thời gian chuẩn xác: '姑且' / '暂且' (tạm thời, tạm gác lại); '即' (liền, lập tức); '即时' (ngay tức khắc, theo thời gian thực); '届时' (đến thời điểm đó - dùng hẹn ngày); '尽早' (càng sớm càng tốt); '就此' (từ đây, nhân đây mà dừng/kết thúc); '历来' / '向来' (từ xưa đến nay); '尚' (vẫn còn, chưa - 尚不明确, 尚有); '随即' (ngay sau đó); '一经' (một khi đã qua bước kiểm tra/phê duyệt... thì - 一经发现, 一经查实); '早日' (sớm - chúc sớm bình phục: 早日康复).",
        "tips": "'届时' và '一经' là hai từ chìa khóa trong thông báo hành chính và thư mời dự hội nghị."
    },
    {
        "order": 14,
        "titleVi": "Chùm phó từ tần suất & tiếp diễn cao cấp: 连连, 屡次, 屡屡, 频, 时而, 时时, 相继, 一个劲（儿）, 一连, 再度",
        "structure": "Phó từ tần suất + Động từ",
        "category": "cau-tu-tu-loai",
        "explanation": "Mô tả tần suất và nhịp độ lặp lại: '连连' (liên hồi, không ngớt - 连连称赞, 连连点头); '屡次' / '屡屡' (năm lần bảy lượt, liên tiếp diễn ra); '频' (thường xuyên, dồn dập - 频发, 频出); '时而' (lúc thì - 時而...時而...); '时时' (luôn luôn, từng giờ từng phút); '相继' (lần lượt tiếp bước nhau - 相继出台, 相继考入); '一个劲（儿）' (khẩu ngữ: cứ cắm đầu miệt mài làm suốt); '一连' (liền tù tì mấy ngày/lần); '再度' (lại một lần nữa - 再度夺冠).",
        "tips": "Phân biệt '屡次' (nhấn mạnh số lần lặp lại nhiều) và '相继' (nhấn mạnh tính kế tiếp nhau của các sự kiện)."
    }
]

TRANSLATIONS_1A = {
    "近年来，两国战略沟通合作日益密切，兄弟情谊愈加深厚。": "Những năm gần đây, quan hệ trao đổi hợp tác chiến lược giữa hai nước ngày càng mật thiết, tình hữu nghị anh em càng thêm sâu sắc bền chặt.",
    "随着阅读的增多，书慧愈加不满足于安居于室，渴望去见识外面的世界。": "Cùng với vốn đọc sách ngày một phong phú, Thư Tuệ càng thêm không cam chịu cảnh an phận thủ thường ru rú trong nhà, mà khao khát được bước ra khám phá thế giới bên ngoài.",
    "经过数百次的舞台历练，他的演技越发纯熟。": "Trải qua hàng trăm lần trui rèn trên sân khấu, diễn xuất của anh ấy ngày càng điêu luyện chín muồi.",
    "缠绵的雨丝，飘洒在青石小巷，越发让人觉得诗意。": "Những sợi mưa giăng giăng vương vấn buông rơi xuống con ngõ nhỏ lát đá xanh, càng khiến lòng người ngập tràn chất thơ.",
    "他的身体已经大体恢复了，我觉得可以进行一些基础性训练了。": "Sức khỏe của anh ấy đại thể đã bình phục rồi, tôi thấy có thể bắt đầu tập một số bài rèn luyện cơ bản.",
    "同类企业中，设备或许大体相似，但是生产效能可能相差悬殊。": "Giữa các doanh nghiệp cùng ngành, trang thiết bị máy móc có thể đại khái tương tự nhau, nhưng hiệu suất sản xuất có thể chênh lệch một trời một vực.",
    "游客因擅自参加高危活动所造成的人身和财产损失，本旅行社概不负责。": "Những thiệt hại về người và của do du khách tự ý tham gia các hoạt động mạo hiểm nguy hiểm gây ra, công ty du lịch chúng tôi hoàn toàn không chịu trách nhiệm.",
    "凡成大事者，必定有坚韧不拔的意志。古今中外，概莫能外。": "Phàm những bậc làm nên việc lớn nhất định phải có ý chí kiên định sắt đá. Từ xưa chí kim, từ đông sang tây, không một ai là ngoại lệ cả.",
    "这部剧除男女主角之外，其他演员皆一人分饰数角，但每个人物特点鲜明，并不会让观众混淆。": "Vở kịch này ngoại trừ cặp đôi nam nữ chính ra, các diễn viên khác đều một người đóng nhiều vai, nhưng mỗi nhân vật đều mang cá tính rõ rệt, không hề khiến khán giả bị nhầm lẫn.",
    "中国瓷器之所以享誉世界，皆因其实用与审美并存。": "Gốm sứ Trung Hoa sở dĩ nức tiếng khắp thế giới, thảy đều nhờ vào sự song hành hài hòa giữa công năng thực dụng và vẻ đẹp thẩm mỹ.",
    "荆门为荆楚文化发祥地之一，文化底蕴深厚，历史古迹遍地皆是。": "Kinh Môn là một trong những cái nôi phát tích của văn hóa Kinh Sở, bề dày văn hóa sâu rộng, di tích lịch sử đâu đâu cũng có.",
    "从广州塔顶楼俯瞰，羊城璀璨的夜景尽收眼底。": "Từ tầng cao nhất của tháp Quảng Châu phóng tầm mắt ngắm nhìn, cảnh đêm rực rỡ hoa lệ của thành Dương Thành thu trọn vào đáy mắt.",
    "村落被青山绿水环绕，尽是些古朴的瓦房和雅致的石桥，没有丝毫现代化的气息，却添了几分宁静与幽然。": "Ngôi làng được non xanh nước biếc ôm ấp bao bọc, toàn là những mái nhà ngói cổ kính và cây cầu đá thanh tao, không chút hơi thở hiện đại, nhưng lại tăng thêm vài phần tĩnh lặng thanh nhã.",
    "在有关部门的大力监管下，存在环境安全隐患的酒店、餐厅等均已完成整改。": "Dưới sự kiểm tra giám sát gắt gao của các cơ quan chức năng, những khách sạn, nhà hàng tiềm ẩn nguy cơ mất an toàn môi trường đều đã hoàn thành việc chấn chỉnh sửa đổi.",
    "市场上某些特殊商品不宜标价的，均须经当地价格主管部门核准。": "Một số mặt hàng đặc thù trên thị trường không tiện niêm yết giá công khai thì thảy đều phải qua cơ quan quản lý giá cả địa phương thẩm định phê duyệt.",
    "那一大堆坏了的电器，他只用了一个晚上的时间，就通通修理好了。": "Cả một đống đồ điện hỏng hóc kia, anh ấy chỉ dùng vỏn vẹn một buổi tối là đã sửa xong tuốt tuồn tuột.",
    "这些事情你通通不要管，你只负责技术革新。": "Mấy chuyện linh tinh này cậu tuốt tuồn tuột đừng bận tâm, cậu chỉ cần tập trung phụ trách đổi mới kỹ thuật thôi.",
    "她对年轻后辈毫无保留，将自己多年来的经验教训统统分享给了大家。": "Cô ấy đối với thế hệ đàn em đi sau không hề giấu giếm chút ngón nghề nào, đem toàn bộ những kinh nghiệm xương máu đúc kết bao năm sẻ chia hết cho mọi người.",
    "他现在是一切为了孩子，什么升职发财换大房子，他统统不去想了。": "Bây giờ anh ấy một lòng một dạ chỉ vì con cái, ba cái chuyện thăng quan phát tài đổi nhà to anh ấy gạt sạch ra khỏi đầu không thèm nghĩ tới.",
    "现在很多孩子都有“唯我为大”的思维方式，这跟父母的过分溺爱有密切的关系。": "Ngày nay rất nhiều đứa trẻ mang tư duy 'ta là rốn của vũ trụ', điều này có mối liên hệ mật thiết với sự nuông chiều quá mức của cha mẹ.",
    "修身之道不唯阅读，品茶、闲谈、对弈、抚琴、练武、游历山水均可养性。": "Đạo tu thân không chỉ có mỗi đọc sách, việc thưởng trà, đàm đạo, chơi cờ, gảy đàn, luyện võ, du ngoạn non nước thảy đều có thể dưỡng tâm bồi tính.",
    "那么多同他一起备考的考生都放弃了，唯独他一个人坚持了下来。": "Bao nhiêu thí sinh cùng ôn thi với anh ấy đều đã bỏ cuộc giữa chừng, duy chỉ có mình anh là kiên trì trụ lại tới cùng.",
    "人的眼睛，能洞察他人，观测周遭的事物，唯独无法窥见自己的真容。": "Đôi mắt con người có thể nhìn thấu thiên hạ, quan sát vạn vật xung quanh, duy chỉ có chân dung đích thực của chính mình là không thể tự soi thấy.",
    "我们村上了岁数的老人几乎都不会用智能手机，唯有老村长是个例外。": "Các cụ cao niên trong làng chúng tôi hầu như chẳng ai biết xài điện thoại thông minh, duy chỉ có cụ trưởng thôn là một ngoại lệ hiếm hoi.",
    "在全球化的激烈竞争中，唯有持续创新才能立于不败之地。": "Trong cuộc cạnh tranh khốc liệt của toàn cầu hóa, chỉ có con đường không ngừng đổi mới sáng tạo mới có thể đứng vững bất bại.",
    "综合来看，外语学习的动机无非两种：融合型动机和工具型动机。": "Nhìn nhận một cách tổng thể, động lực học ngoại ngữ chẳng qua cũng chỉ có hai loại: động lực hòa nhập văn hóa và động lực công cụ thực dụng.",
    "邻居跟我偶然碰见时会闲聊几句，说的无非是些家长里短的事情。": "Hàng xóm khi tình cờ chạm mặt tôi cũng trò chuyện dăm ba câu, nói qua nói lại chẳng qua cũng chỉ quanh quẩn mấy chuyện vụn vặt gia đình.",
    "国务院明确规定，我国的“驰名商标”工作一概由国家商标局负责。": "Quốc vụ viện quy định rõ ràng rằng, công tác quản lý 'Nhãn hiệu nổi tiếng' của nước ta hoàn toàn do Cục Nhãn hiệu Quốc gia thống nhất phụ trách.",
    "小夫妻俩决定婚礼一切从简，只摆几桌酒席，婚车和接亲环节一概取消。": "Đôi vợ chồng trẻ quyết định hôn lễ mọi thứ làm giản tiện, chỉ bày biện vài mâm cỗ ấm cúng, còn xe hoa rước dâu và các thủ tục rườm rà thì hủy bỏ toàn bộ.",
    "出于保护当事人的考虑，我们隐去了其真实姓名，姑且以“张某”代称。": "Xuất phát từ việc bảo vệ đương sự, chúng tôi đã giấu kín danh tính thật, tạm thời gọi bằng cái tên 'Trương mỗ'.",
    "我给您简单分析一下吧，您姑且一听，要是不对，权当我没说。": "Để tôi phân tích sơ qua giúp bác nhé, bác tạm lắng tai nghe thử, nếu không đúng thì coi như tôi chưa từng nói gì.",
    "“蜜月游”愈发流行，不少年轻人办完酒席即启程旅行。": "Trào lưu 'Du lịch trăng mật' ngày càng thịnh hành, không ít bạn trẻ tiệc cưới vừa tàn là lập tức xách ba lô lên đường du ngoạn.",
    "在4G峰值速度下，下载一部1GB大小的高清电影需要1分钟左右，而在5G条件下只需几秒即可。": "Ở tốc độ đỉnh của mạng 4G, tải một bộ phim độ nét cao dung lượng 1GB mất khoảng 1 phút, thế nhưng sang mạng 5G chỉ cần vài giây là xong ngay.",
    "气象局在暴雨来临前，通过网络、电视、广播等多种媒介，即时发布有关暴雨的预警信号。": "Cục khí tượng trước khi mưa bão ập tới đã thông qua mạng internet, truyền hình, phát thanh để lập tức phát đi các tín hiệu cảnh báo giông bão theo thời gian thực.",
    "本协议在履行过程中，如若发生未曾约定的情况，届时由双方共同友好商定。": "Trong quá trình thực hiện bản thỏa thuận này, nếu phát sinh tình huống chưa được quy định trước, đến lúc đó đôi bên sẽ cùng hữu nghị bàn thảo định đoạt.",
    "大会将于9月10日至18日在北京举行，届时将会有近800名国外代表与会。": "Đại hội sẽ được tổ chức từ ngày 10 đến 18 tháng 9 tại Bắc Kinh, đến thời điểm đó sẽ có gần 800 đại biểu nước ngoài tới tham dự.",
    "家长应尽早让孩子参与家务劳动，培养他们的责任感和自理能力。": "Các bậc phụ huynh nên sớm để con cái tham gia vào công việc nhà, bồi dưỡng cho trẻ tinh thần trách nhiệm và năng lực tự lập.",
    "外出旅行应提前确定行程并尽早预约购票，以防票量不足或票价上涨。": "Đi du lịch xa nên chốt lịch trình từ trước và đặt mua vé càng sớm càng tốt để phòng trường hợp cháy vé hoặc giá vé tăng cao.",
    "相聚的时光总是短暂的，丰盛的晚餐过后大家就此告别。": "Khoảnh khắc hội ngộ sum vầy lúc nào cũng ngắn ngủi, sau bữa tối thịnh soạn mọi người nhân đây nói lời chia tay tạm biệt.",
    "虽然油气勘探工作屡遭失败，但是地质学家们并未就此止步，反倒越挫越勇。": "Tuy công tác thăm dò dầu khí liên tục thất bại, nhưng các nhà địa chất học không hề dừng bước tại đây, trái lại càng vấp ngã càng thêm kiên cường.",
    "“绿肥红瘦”四字是李清照《如梦令》一词的点睛之笔，历来为世人所称道。": "Bốn chữ 'lục phì hồng sấu' (lá xanh đẫy đà hoa hồng tàn tạ) là nét chấm phá đắt giá trong bài từ 'Như Mộng Lệnh' của Lý Thanh Chiếu, xưa nay luôn được người đời hết lời ca tụng.",
    "苏州历来是经济富饶的鱼米之乡，与杭州齐名，并称“苏杭”。": "Tô Châu từ xưa đến nay vốn là vùng đất trù phú màu mỡ ngập tràn cá tôm lúa gạo, sánh ngang với Hàng Châu và được gọi chung là 'Tô - Hàng'.",
    "当时我年纪尚幼，许多事情已然模糊不清，但故乡染满绿的庭院，是记忆深处永远的乡愁。": "Hồi đó tôi tuổi còn thơ dại, nhiều chuyện xưa nay đã phai nhòa mông lung, nhưng khu vườn ngập tràn sắc xanh nơi quê nhà mãi là nỗi nhớ cố hương da diết sâu thẳm trong ký ức.",
    "截至目前，搜救工作尚未发现幸存人员，事故原因尚待调查。": "Tính đến thời điểm hiện tại, công tác tìm kiếm cứu nạn vẫn chưa phát hiện người sống sót, nguyên nhân tai nạn vẫn còn đang chờ điều tra làm rõ.",
    "她犹豫了一下，随即拿起了电话，把这件事报告给总经理。": "Cô ấy ngập ngừng đôi chút, ngay sau đó nhấc điện thoại lên báo cáo sự việc cho tổng giám đốc.",
    "我听闻临近扬州的泰州，早茶亦颇有特色，随即驱车从扬州前往泰州。": "Tôi nghe nói thành phố Thái Châu nằm sát nách Dương Châu cũng có món trà sớm rất độc đáo, liền ngay lập tức lái xe từ Dương Châu sang Thái Châu thưởng thức.",
    "孙老板向来一言九鼎，因此在商界信誉很高。": "Ông chủ Tôn từ xưa đến nay nói một là một nói hai là hai, lời nói nặng tựa cửu đỉnh, vì thế trên thương trường uy tín vô cùng cao trọng.",
    "他深居简出，向来不喜与外界交往。": "Ông ấy sống ẩn dật khép kín, từ trước tới giờ vốn không thích giao thiệp với thế giới bên ngoài.",
    "绿色农场种植出的果蔬天然无公害，一经上市便供不应求。": "Rau củ quả do nông trường xanh canh tác hoàn toàn tự nhiên không độc hại, vừa mới tung ra thị trường một cái là đã cháy hàng cung không đủ cầu.",
    "《红楼梦》这部经典名著又要翻拍的消息一经发布，即引起社会热议。": "Tin tức bộ danh tác kinh điển 'Hồng Lâu Mộng' sắp sửa được bấm máy làm lại vừa mới phát đi một cái là lập tức làm xôn xao dư luận xã hội.",
    "鉴于此问题情况复杂、涉及面广，本文限于篇幅，暂且不做讨论。": "Xét thấy vấn đề này tình hình phức tạp lại dính líu đến diện rộng, bài viết này do khuôn khổ dung lượng có hạn nên tạm thời không đi sâu bàn luận.",
    "任务推进遇到瓶颈时，不妨暂且搁置细节问题，集中精力解决主要问题。": "Khi tiến độ công việc gặp phải nút thắt cổ chai, chi bằng hãy tạm gác các chi tiết vụn vặt sang một bên để dồn toàn lực tháo gỡ vấn đề mấu chốt nhất.",
    "我们期待她的新作早日问世，并且预祝她在文学创作上取得更大的成功。": "Chúng tôi vô cùng mong đợi tác phẩm mới của cô ấy sớm ngày ra mắt công chúng, đồng thời chúc cô gặt hái được những thành tựu rực rỡ hơn nữa trên văn đàn.",
    "孩子们自发来到病房里看望老师，感谢老师的辛勤付出并祝愿老师早日康复。": "Lũ trẻ đã tự rủ nhau đến tận phòng bệnh thăm cô giáo, bày tỏ lòng biết ơn trước sự tận tụy của cô và chúc cô sớm ngày bình phục khỏe mạnh.",
    "这家店的饭菜不但量大实惠，而且色香味俱全，每一个来吃的人都连连称赞。": "Cơm canh quán này chẳng những đĩa đầy ụ giá cả phải chăng, mà sắc hương vị đều trọn vẹn, bất cứ ai từng tới ăn cũng đều tấm tắc khen ngợi không ngớt.",
    "杂技艺术节上，各地顶尖的杂技演员各显身手，引得现场惊呼不断、掌声连连。": "Tại lễ hội nghệ thuật xiếc, các nghệ sĩ xiếc đỉnh cao khắp nơi đua nhau trổ tài xuất chúng, khiến cả hội trường ồ lên kinh ngạc không ngớt và vỗ tay rào rào liên hồi.",
    "嘉宾因说话屡次被主持人打断，已面露愠色。": "Vị khách mời do lời nói năm lần bảy lượt bị MC cắt ngang nên trên gương mặt đã thoáng lộ rõ vẻ tức giận bực bội.",
    "他的电影作品受到海内外市场的欢迎，屡次获得国际影展奖项。": "Các tác phẩm điện ảnh của ông được thị trường trong và ngoài nước đón nhận nồng nhiệt, liên tục ẵm các giải thưởng lớn tại các liên hoan phim quốc tế.",
    "凭借着高超的技艺和精巧的构思，民间艺术家的作品在国内外赛事中屡屡获奖。": "Nhờ kỹ nghệ siêu phàm và ý tưởng bài trí tài hoa, tác phẩm của nghệ nhân dân gian này liên tiếp rinh về giải thưởng tại các cuộc thi trong và ngoài nước.",
    "这一服装品牌将非遗元素融入现代设计，屡屡在时装周上惊艳亮相。": "Thương hiệu thời trang này đã khéo léo lồng ghép các yếu tố di sản phi vật thể vào thiết kế đương đại, liên tục tạo nên những màn xuất hiện mãn nhãn tại các tuần lễ thời trang.",
    "近年来，我院师生在各类学科竞赛中屡获佳绩，捷报频传。": "Những năm gần đây, thầy trò học viện chúng tôi liên tục gặt hái thành tích vang dội tại các kỳ thi học thuật, tin báo thắng trận bay về dồn dập.",
    "这里以前是沙尘暴频发的地区，通过植树造林、补绿复绿，现已成为国家级生态文明示范区。": "Nơi đây trước kia vốn là điểm nóng thường xuyên bùng phát bão cát, nhờ nỗ lực trồng cây gây rừng phủ xanh đất trống, nay đã vươn mình trở thành khu văn minh sinh thái kiểu mẫu cấp quốc gia.",
    "天空布满阴云，时而落下几滴雨，未带来一丝凉爽，却闷得让人喘不过气来。": "Bầu trời giăng kín mây xám xịt, chốc chốc lại lất phất rơi vài hạt mưa, chẳng đem lại chút mát mẻ nào mà lại oi nồng đến mức khiến người ta nghẹt thở.",
    "他凝神望着前方连绵的青山，时而眉头微蹙，时而喜上眉梢，不知思绪飘到了何方。": "Anh ấy chăm chú ngắm nhìn rặng núi xanh biếc trập trùng phía trước, lúc thì khẽ chau mày đăm chiêu, lúc lại rạng rỡ niềm vui nơi khóe mắt, chẳng rõ dòng suy nghĩ đã trôi dạt tới phương trời nào.",
    "对这些好心人的善举，受帮助者时时感念于心，希望有朝一日能回报恩人。": "Trước nghĩa cử cao đẹp của những tấm lòng vàng, người được cưu mang luôn luôn khắc cốt ghi tâm, mong sao có một ngày được đền đáp ơn sâu nghĩa nặng.",
    "工作中他是严师，教学一丝不苟；生活中他又像个老父亲，时时关心我们的身心健康。": "Trong công việc thầy là một người thầy nghiêm khắc dạy dỗ đâu ra đấy; còn ngoài đời thường thầy lại như người cha già, luôn luôn ân cần hỏi han sức khỏe thể chất lẫn tinh thần của chúng tôi.",
    "如果员工相继辞职，老板必须予以重视，找寻员工流失的真正原因。": "Nếu nhân viên cứ lần lượt nối gót nhau nộp đơn xin thôi việc, ông chủ nhất định phải hết sức lưu tâm, tìm cho ra cội nguồn thực sự của việc chảy máu chất xám.",
    "金秋九月，北京戏剧舞台异彩纷呈，相继展演了精品剧目114部。": "Mùa thu tháng Chín, sân khấu kịch Bắc Kinh rực rỡ sắc màu, đã lần lượt công diễn 114 vở kịch kinh điển xuất sắc.",
    "大嫂在旁边一个劲使眼色，示意哥哥不要再说下去了。": "Chị dâu đứng bên cạnh cứ liên tục nháy mắt ra hiệu, bảo anh trai đừng có bốc đồng nói thêm lời nào nữa.",
    "孩子不能一个劲儿地闷头苦学，适当的休闲和锻炼都是很有必要的。": "Trẻ con không thể cứ cắm đầu cắm cổ học vùi học dập suốt ngày, việc thư giãn hợp lý và rèn luyện thể chất là hết sức cần thiết.",
    "为了尽快研制出特效药，他常常在实验室里一连奋战十几个小时。": "Để mau chóng điều chế thành công loại thuốc đặc trị, anh ấy thường xuyên ở lì trong phòng thí nghiệm quần quật chiến đấu liền mười mấy tiếng đồng hồ.",
    "大水靠在沙发上，一连打了好几个哈欠，困得睁不开眼。": "Đại Thủy ngả lưng vào ghế sofa, ngáp liền một hơi mấy cái dài, buồn ngủ díu cả hai mắt lại.",
    "时隔12年，中国队再度捧起冠军奖杯。": "Cách biệt tròn 12 năm đằng đẵng, đội tuyển Trung Quốc lại một lần nữa giơ cao chiếc cúp vô địch danh giá.",
    "由于身体抱恙，她一度放弃歌唱事业。后来在家人的支持下，她再度鼓起勇气，站上舞台。": "Do sức khỏe giảm sút vì bạo bệnh, cô ấy từng có lúc phải từ bỏ sự nghiệp ca hát. Về sau nhờ sự tiếp sức của gia đình, cô đã lại một lần nữa lấy hết dũng khí bước lên ánh đèn sân khấu.",
    # 001
    "奥运场馆开工之前，就要考虑到后奥运时代的需求。": "Trước khi khởi công các nhà thi đấu Olympic, đã phải tính đến nhu cầu sử dụng của thời kỳ hậu Olympic.",
    "市长对老人们嘘寒问暖，并亲手将慰问品送到老人手中。": "Thị trưởng ân cần thăm hỏi các cụ già, và đích thân trao tận tay những phần quà thăm hỏi cho các cụ.",
    # 002
    "新时代农民的价值观、消费观、审美观都和以往有了很大的不同。": "Giá trị quan, quan niệm tiêu dùng và gu thẩm mỹ của người nông dân thời đại mới đều đã có sự khác biệt rất lớn so với trước kia.",
    "只给孩子花钱却不花时间陪伴孩子的家长同样是小气鬼。": "Những bậc cha mẹ chỉ chịu chi tiền mà không dành thời gian ở bên con cái thì cũng là những kẻ keo kiệt bủn xỉn mà thôi.",
    "我的导师在学术界和产业界都享有崇高的声望。": "Người thầy hướng dẫn của tôi được hưởng uy tín vô cùng cao trọng ở cả giới học thuật lẫn giới công nghiệp.",
    "经过七个小时的飞行，我终于在异国安然落地。": "Trải qua 7 giờ đồng hồ bay, cuối cùng tôi đã hạ cánh an toàn bình yên nơi đất khách quê người.",
    "今年的“体坛风云人物”颁奖仪式特别隆重。": "Lễ trao giải 'Nhân vật tiêu biểu làng thể thao' năm nay diễn ra đặc biệt long trọng.",
    "本公司的产品多年来广为消费者称赞。": "Sản phẩm của công ty chúng tôi suốt nhiều năm qua được đông đảo người tiêu dùng hết lời khen ngợi.",
    "以公有制为主体、多种所有制经济共同发展,是中国现阶段的基本经济制度。": "Lấy chế độ công hữu làm chủ thể, nhiều thành phần kinh tế cùng phát triển là chế độ kinh tế cơ bản trong giai đoạn hiện nay của Trung Quốc.",
    # 003
    "他巴不得早点儿退休，好能到处游山玩水。": "Ông ấy chỉ mong sao được nghỉ hưu sớm một chút, để có thể đi chu du thưởng ngoạn non nước khắp nơi.",
    "在外漂泊多年的游子归心似箭，巴不得一步跨进家门。": "Người con xa xứ phiêu bạt nhiều năm lòng dạ nóng như lửa đốt, chỉ mong sao một bước nhảy ngay vào đến cửa nhà.",
    "一种艺术风格的形成并非一蹴而就，必须经历一个渐进发展的过程。": "Sự hình thành của một phong cách nghệ thuật tuyệt nhiên không thể một bước là xong, mà phải trải qua một quá trình phát triển tiệm tiến lâu dài.",
    "你之所以落选，并非你不优秀，而是你的风格和他们的需求不完全匹配。": "Sở dĩ bạn không trúng tuyển tuyệt đối không phải vì bạn kém cỏi, mà là phong cách của bạn không hoàn toàn khớp với nhu cầu của họ.",
    "八折优惠仅限周一至周五使用，法定节假日除外。": "Ưu đãi giảm giá 20% chỉ áp dụng từ thứ Hai đến thứ Sáu, ngoại trừ các ngày nghỉ lễ theo luật định.",
    "在场各位皆是西装革履，只有一人除外，穿着十分随意。": "Những người có mặt tại hội trường ai nấy đều âu phục chỉnh tề, chỉ duy nhất một người ngoại lệ, ăn mặc vô cùng tùy ý.",
    "他是个啥也不懂的毛头小子，你犯不着跟他一般见识。": "Nó chỉ là thằng nhóc miệng còn hôi sữa chẳng biết gì, bạn việc gì phải chấp nhặt so đo với nó làm chi.",
    "你们俩打小就认识，为了这么点儿小事闹翻，犯不着。": "Hai đứa quen biết nhau từ tấm bé, vì chút chuyện cỏn con này mà cãi cọ trở mặt thì thật chẳng đáng chút nào.",
    "现在是公司发展的关键时期，你犯得着为这些小事分心吗？": "Hiện tại đang là giai đoạn then chốt cho sự phát triển của công ty, bạn có đáng phải bận lòng phân tâm vì mấy chuyện vụn vặt này không?",
    "人家好心好意给你提些意见，你这么激动，犯得着吗？": "Người ta có lòng tốt góp ý cho bạn, bạn kích động giãy nảy lên như vậy liệu có đáng hay không?",
    "一开始项目推动得非常缓慢，我们恨不得24小时都在工作。": "Thời gian đầu dự án triển khai vô cùng chậm chạp, chúng tôi thèm muốn đến mức chỉ ước một ngày có thể làm việc cả 24 tiếng đồng hồ.",
    "大家的学习热情很高，恨不得一下子把所有的先进技术都学到手。": "Tinh thần học hỏi của mọi người rất cao, ai nấy đều nóng lòng muốn một phát học hết sạch toàn bộ công nghệ tiên tiến vào tay.",
    "此事可否容我思索几日，再行答复？": "Chuyện này liệu có thể cho phép tôi suy nghĩ vài hôm rồi mới hồi đáp được chăng?",
    "关于先生会上所言，学生尚有不明之处，可否向先生进一步请教？": "Về những điều thầy phát biểu trong cuộc họp, học trò vẫn còn chỗ chưa thấu suốt, liệu có thể thỉnh giáo thầy sâu hơn được chăng?",
    "我申请与其当面对质，不知可否？": "Tôi xin phép được đối chất trực tiếp với anh ta, không rõ liệu có được chấp thuận chăng?",
    "王安忆对上海人的观察和描写非常细腻，可谓“入木三分”。": "Sự quan sát và ngòi bút miêu tả của Vương An Ức về con người Thượng Hải vô cùng tinh tế, quả đúng là đạt tới độ 'sâu sắc lạ thường'.",
    "《昆虫记》知识性、趣味性、哲理性兼具，真可谓是科学与艺术相结合的典范。": "Tác phẩm 'Côn trùng ký' hội tụ đủ cả tính tri thức, tính thú vị lẫn tính triết lý, quả thật xứng danh là hình mẫu kết hợp mẫu mực giữa khoa học và nghệ thuật.",
    "在成长的道路上，免不了会遇到各种各样的问题。": "Trên con đường trưởng thành, khó tránh khỏi việc sẽ phải đối mặt với muôn vàn vấn đề trắc trở khác nhau.",
    "这件事要是让他知道，一顿数落是免不了的。": "Chuyện này nếu để ông ấy biết được, thì một trận la mắng trách móc là điều khó mà tránh khỏi.",
    "所谓难得糊涂，并非是对生活的无奈妥协，而是一种张弛有度的处世之道。": "Cái gọi là 'khó được hồ đồ' tuyệt nhiên không phải là sự thỏa hiệp bất lực trước cuộc đời, mà là một thuật đối nhân xử thế biết co biết duỗi.",
    "这家公司所谓的产品升级，不过是给商品换了一个更华丽的包装。": "Cái gọi là 'nâng cấp sản phẩm' của công ty này chẳng qua chỉ là khoác cho món hàng một lớp bao bì lộng lẫy hơn mà thôi.",
    "引进先进技术与优化管理流程后，各部门工作效率均有所提高。": "Sau khi du nhập kỹ thuật tiên tiến và tối ưu hóa quy trình quản lý, hiệu suất làm việc của các phòng ban đều có phần được nâng cao.",
    "倘若事态紧急，无暇向上请示，你大可自行决断，不必有所顾虑。": "Nếu như tình thế khẩn cấp không kịp xin chỉ thị cấp trên, bạn hoàn toàn có thể tự mình quyết đoán, không cần phải mang nỗi âu lo gì.",
    "限于作者水平，如有不当之处还望专家予以批评指正。": "Do trình độ của tác giả còn hạn chế, nếu có chỗ nào chưa thỏa đáng, kính mong các chuyên gia tận tình chỉ giáo và phê bình sửa chữa cho.",
    "对于原告提出的高昂赔付要求，法院并未予以支持。": "Đối với yêu cầu đòi bồi thường với số tiền quá cao do nguyên đơn đưa ra, tòa án đã không chấp nhận phán quyết ủng hộ.",
    # 004
    "我校教育质量上乘，办学几十年间为国家培养、输送了大批优秀人才。": "Trường chúng tôi chất lượng giáo dục hàng đầu, trong suốt mấy chục năm hoạt động đã đào tạo và cung cấp cho đất nước vô số nhân tài kiệt xuất.",
    "我公司始终秉持“以客户为中心”的理念，致力于为客户提供最优质的服务。": "Công ty chúng tôi trước sau luôn kiên trì giữ vững quan điểm 'lấy khách hàng làm trung tâm', dốc toàn lực đem lại dịch vụ tối ưu nhất cho quý khách.",
    # 005
    "“古典小说”鼎盛于明清时期，彼时涌现了如四大名著等众多经典之作。": "Thể loại 'Tiểu thuyết cổ điển' phát triển rực rỡ nhất vào thời Minh - Thanh, thời bấy giờ đã xuất hiện hàng loạt danh tác kinh điển như Tứ đại kỳ thư.",
    "提起朝阳，人们往往会想到北京的朝阳区。然而我们今日前往参观的此“朝阳”非彼“朝阳”，乃是被誉为“三燕古都”的辽宁省朝阳市。": "Nhắc tới Triều Dương, người ta thường liên tưởng ngay đến quận Triều Dương ở Bắc Kinh. Thế nhưng địa danh 'Triều Dương' hôm nay chúng ta ghé thăm không phải là 'Triều Dương' kia, mà chính là thành phố Triều Dương thuộc tỉnh Liêu Ninh - nơi từng được xưng tụng là Cố đô Tam Yến.",
    "在商务谈判中，应尽量做到知己知彼，这样才能争取到最大的利益。": "Trong đàm phán thương mại, nên cố gắng hết sức làm sao để 'biết người biết ta', có như vậy mới tranh thủ được nguồn lợi ích to lớn nhất.",
    "你们觉得这么着好就这么办，不必再来问我的意见了。": "Các bạn thấy làm thế này ổn thì cứ triển khai như thế đi, không cần phải hỏi lại ý kiến của tôi nữa đâu.",
    "那地方你人生地不熟的，这么着吧，我陪你一起去看看。": "Nơi đó bạn đất khách quê người lạ nước lạ cái, hay là thế này đi, tôi cùng đi với bạn tới xem thử.",
    "兹证明李莉女士系本单位正式员工，已连续在本单位工作十年。": "Nay xin chứng nhận bà Lý Lợi là nhân viên chính thức của đơn vị chúng tôi, đã công tác liên tục tại cơ quan tròn mười năm.",
    "受有关机构委托，兹有以下标的拟予以转让，现公告如下，欢迎合格投标人参加该项目投标。": "Nhận ủy thác từ cơ quan hữu quan, nay có danh mục tài sản dưới đây dự kiến chuyển nhượng, trân trọng thông báo như sau, hoan nghênh các bên dự thầu đủ điều kiện nộp hồ sơ đấu thầu dự án.",
    # 006
    "历史学家的任务之一是在浩瀚的史料中挖掘出何时、何地发生了何种事件。": "Một trong những sứ mệnh của các nhà sử học là khai quật trong biển tư liệu mênh mông để tìm ra vào lúc nào, tại nơi đâu đã phát sinh biến cố gì.",
    "这座滨江小城魅力何在？因何引得诸多文人骚客留下脍炙人口的名篇？": "Sức quyến rũ của thành phố nhỏ ven sông này nằm ở chỗ nào? Vì cớ gì lại thu hút biết bao tao nhân mặc khách lưu lại những áng thơ văn truyền tụng muôn đời?",
    "他夜里翻来覆去地想着这件事，可是还是不知道该怎么着才好。": "Đêm nằm trằn trọc lật qua lật lại suy nghĩ về chuyện này, nhưng anh ấy vẫn chẳng biết rốt cuộc phải xử trí làm sao cho ổn thỏa.",
    "你说她半天在那儿一声不吭，是生气了还是怎么着？": "Bạn xem cô ấy ngồi đực ra đó suốt cả buổi chẳng nói chẳng rằng, là đang giận dỗi hay là làm sao thế nhỉ?",
    # 007
    "经过初赛、复赛和决赛，大赛产生了“十佳歌手”和若干“优秀歌手”。": "Trải qua các vòng sơ khảo, bán kết và chung kết, hội thi đã chọn ra 'Mười ca sĩ xuất sắc nhất' cùng một số giải thưởng 'Ca sĩ triển vọng'.",
    "她一生著有长篇小说七部，另有中短篇小说、散文、诗歌、随笔若干。": "Cả cuộc đời bà đã trước tác 7 bộ tiểu thuyết dài tập, bên cạnh đó còn có một số truyện ngắn, tản văn, thi ca và tùy bút khác.",
    # 008
    "该项目的延期是由多重原因所导致的，包括预算不足、人员短缺等。": "Việc dự án này bị chậm tiến độ là do nhiều tầng nguyên nhân gây nên, bao gồm ngân sách eo hẹp và nhân sự thiếu hụt.",
    "她们团队克服重重困难和阻碍，出色地完成了艰巨的任务。": "Đội ngũ của các cô ấy đã vượt qua muôn trùng gian nan trắc trở, hoàn thành xuất sắc nhiệm vụ vô cùng nặng nề.",
    "他想找一截木头做个镇纸。": "Anh ấy muốn tìm một khúc gỗ để đẽo thành chiếc chặn giấy.",
    "他看到这里简陋的生活环境，心里顿时凉了半截。": "Nhìn thấy hoàn cảnh sinh hoạt tồi tàn nơi đây, lòng anh ấy bỗng chốc nguội lạnh đi mất một nửa.",
    "迎面走来一个身着白色T恤的女学生，白皙的额头上垂落着一缕秀发。": "Đi đón đầu là một nữ sinh mặc chiếc áo phông trắng, trên vầng trán trắng ngần buông lơi một lọn tóc mượt mà.",
    "忽地起了一阵微风，送来缕缕清香，将所有的烦恼瞬间驱散。": "Chợt một làn gió nhẹ thoảng qua, đưa tới từng luồng hương thơm thoang thoảng, xua tan biến mọi nỗi ưu phiền trong chốc lát.",
    "科研和科普是两码事。杰出的科学家未必能写出好的科普作品，优秀的科普作家也不一定能做好科研工作。": "Nghiên cứu khoa học và phổ biến kiến thức khoa học là hai chuyện hoàn toàn khác nhau. Nhà khoa học kiệt xuất chưa chắc đã viết nên tác phẩm phổ biến hay, và tác giả viết sách khoa học đại chúng cừ khôi cũng chưa hẳn đã làm tốt công tác nghiên cứu chuyên sâu.",
    "虽然你们私交很好，但工作上的事情还是应该一码归一码，公事公办。": "Tuy quan hệ tình cảm riêng của hai người rất khăng khít, nhưng việc công thì chuyện nào ra chuyện nấy, cứ theo phép công mà làm.",
    "权利与义务犹如一枚硬币的两面，相互依存，密不可分。": "Quyền lợi và nghĩa vụ tựa như hai mặt của cùng một đồng xu, nương tựa lẫn nhau và gắn bó không thể tách rời.",
    "他工作非常出色，十年里共获得五枚奖章。": "Anh ấy cống hiến công tác vô cùng xuất sắc, trong suốt mười năm đã vinh dự đoạt được 5 tấm huân chương.",
    "苏州有一对老夫妻，子女们平日里各为自己的一摊事忙活，只有节假日才有机会团聚。": "Ở Tô Châu có một đôi vợ chồng già, con cái ngày thường ai nấy đều túi bụi với mớ việc riêng của mình, chỉ có dịp lễ tết mới có dịp quây quần đoàn tụ.",
    "公司的事已经让他焦头烂额，家中还另有一摊，他感到身心俱疲。": "Chuyện ở cơ quan đã khiến anh ấy sứt đầu mẻ trán, trong nhà lại bề bộn thêm một đống việc khác, khiến anh cảm thấy kiệt quệ cả thể xác lẫn tinh thần.",
    "要制成一丸药，需用上三十多种原料并经过多道工序。": "Muốn luyện thành một viên hoàn thuốc này, cần phải dùng tới hơn 30 loại dược liệu và trải qua nhiều công đoạn chế biến nghiêm ngặt.",
    "这个药每日三次，每次六丸，餐后半小时服用。": "Thuốc này mỗi ngày uống 3 lần, mỗi lần 6 viên hoàn, uống sau bữa ăn nửa tiếng.",
    "今天《人民日报》上刊登的一则新闻，令我大吃一惊。": "Mẩu tin tức đăng trên tờ 'Nhân Dân Nhật Báo' hôm nay đã khiến tôi vô cùng kinh ngạc.",
    "在不到两小时的演讲过程中，他至少引用了20则古代典故。": "Trong suốt bài diễn thuyết chưa đầy hai tiếng đồng hồ, ông ấy đã trích dẫn ít nhất 20 mẩu điển cố cổ xưa.",
    "历经一年，长乐村建成了一幢两层高的标准化教学楼。": "Trải qua một năm ròng rã, thôn Trường Lạc đã dựng nên một tòa nhà học tập hai tầng đạt chuẩn hóa.",
    "医院今年新建职工宿舍三幢，医技大楼两幢。": "Bệnh viện năm nay xây mới 3 tòa nhà ký túc xá cho cán bộ công nhân viên và 2 tòa nhà kỹ thuật y tế.",
    "法官必须具有超乎寻常的耐心和细心，才能办好每一宗案件。": "Thẩm phán nhất định phải có lòng kiên nhẫn và sự cẩn trọng phi thường thì mới có thể xét xử trọn vẹn từng vụ án một.",
    "他匆匆赶往机场，准备飞去香港谈宗生意。": "Anh ấy hối hả chạy ra sân bay, chuẩn bị bay sang Hồng Kông để bàn thảo một thương vụ làm ăn lớn.",
    # 009
    "了解了我的饮食习惯以后，那位医生将我好一通批评，说我没有管住嘴。": "Sau khi nắm rõ thói quen ăn uống của tôi, vị bác sĩ đó đã phê bình tôi một hồi ra trò, bảo tôi không biết kiêng khem giữ mồm giữ miệng.",
    "因为他的失误，公司利益受到了重大损失，老板把他狠狠训了一通。": "Bởi sai sót của anh ta khiến lợi ích của công ty bị tổn thất nặng nề, sếp đã mắng cho anh ta một trận tơi bời.",
    # 010
    "旅游大数据显示，今年一季度辽宁省共接待游客1.71亿人次，同比增长68.2%。": "Dữ liệu du lịch lớn cho thấy, quý một năm nay tỉnh Liêu Ninh đã đón tiếp tổng cộng 171 triệu lượt khách du lịch, tăng trưởng 68,2% so với cùng kỳ năm ngoái.",
    "各大图书馆的古旧书刊，因近年借阅人次大幅增加，损坏非常严重。": "Sách báo tài liệu cổ tại các thư viện lớn, do những năm gần đây lượt người tới mượn đọc tăng vọt, nên tình trạng hư hại diễn ra hết sức nghiêm trọng.",
    # 011
    "当他们第一次品尝这道精致的菜肴时，大为惊叹，味蕾感到前所未有的满足。": "Khi lần đầu nếm thử món ăn tinh xảo này, họ đã vô cùng kinh ngạc thán phục, vị giác đón nhận sự thỏa mãn chưa từng có.",
    "该歌手的演唱会门票，每张均以高价售出，但其表演水平并不高，观众看后大为不满。": "Vé xem đêm nhạc của ca sĩ đó chiếc nào cũng bán với giá cắt cổ, nhưng trình độ biểu diễn lại chẳng ra sao, khán giả xem xong đều hết sức bất mãn.",
    "与高手过招时须分外小心，万不可轻举妄动。": "Khi giao đấu với các bậc cao thủ cần phải đặc biệt cẩn trọng, tuyệt đối không được khinh suất manh động.",
    "由于周边建筑都比较低矮，这座大楼显得分外高大。": "Do các công trình xung quanh đều khá thấp bé, nên tòa cao ốc này trông nổi bật lên sừng sững khác thường.",
    "拥有一双发现美的眼睛，在平淡生活中捕捉到一点一滴的美好，是何等幸运！": "Sở hữu một đôi mắt biết nhìn ra cái đẹp, nắm bắt từng chút điều tươi đẹp trong cuộc sống bình dị, điều đó mới may mắn biết bao!",
    "在地形条件复杂的地区修筑一条长距离的铁路，不仅需攻克技术难题，而且投资巨大、耗时耗力，是何等地不容易啊！": "Việc thi công một tuyến đường sắt đường dài tại khu vực có địa hình hiểm trở phức tạp, chẳng những phải đột phá các nút thắt kỹ thuật mà vốn đầu tư lại khổng lồ, hao tài tốn lực, quả thực là gian nan biết nhường nào!",
    "即使在极度困难的条件下，他仍执着地追求着自己的艺术理想。": "Ngay cả trong hoàn cảnh cùng cực gian truân, anh ấy vẫn kiên định theo đuổi lý tưởng nghệ thuật của riêng mình.",
    "他这段时间一直极度紧张和焦虑，现在终于放松下来了。": "Khoảng thời gian này anh ấy luôn trong trạng thái cực kỳ căng thẳng và lo âu, giờ đây cuối cùng cũng đã thả lỏng được tinh thần.",
    "在会议上，他提出的解决方案大家都表示赞成，只有副总经理一个人极力反对。": "Tại cuộc họp, phương án giải quyết do anh ấy đề xuất ai nấy đều tán thành, duy chỉ có mình phó tổng giám đốc là ra sức kịch liệt phản đối.",
    "他极力想忍住，但疼痛还是使他叫出声来。": "Anh ấy đã gắng hết sức kìm nén, nhưng cơn đau đớn vẫn khiến anh phải bật thốt lên thành tiếng.",
    "今年这套试卷注重考查学生灵活运用语言知识的能力，整体难度略高于历年考题。": "Đề thi năm nay chú trọng kiểm tra năng lực vận dụng linh hoạt kiến thức ngôn ngữ của học sinh, độ khó tổng thể hơi cao hơn một chút so với đề thi các năm trước.",
    "主人的审美意趣如何，从其所着的衣饰和家中的陈设，便可略知一二。": "Gu thẩm mỹ của gia chủ thế nào, chỉ cần nhìn qua trang phục họ mặc và cách bày biện trong nhà là có thể hiểu được đôi phần.",
    "他脸上挂着浅浅笑意，听到问题后总会先略微思考一下，再不紧不慢地作答。": "Trên gương mặt anh ấy nở nụ cười nhẹ, khi nghe câu hỏi luôn trầm ngâm suy nghĩ một lát rồi mới thong thả trả lời.",
    "志愿者的热情如融融阳光，为这略微有些寒冷的清晨带来了暖意。": "Sự nhiệt tình của các tình nguyện viên tựa như ánh nắng ấm áp chan hòa, xua tan cái se lạnh của buổi sớm mai.",
    "林青自幼对木雕颇感兴趣，六岁起即拜当地的匠人为师，潜心学习雕刻技艺。": "Lâm Thanh từ nhỏ đã khá hứng thú với nghệ thuật chạm khắc gỗ, từ 6 tuổi đã bái nghệ nhân địa phương làm thầy, dốc lòng dùi mài kỹ nghệ điêu khắc.",
    "城市民宿往往隐于闹市，因其风格独特，活动自由，如今颇受顾客青睐。": "Các homestay trong đô thị thường ẩn mình giữa phố xá sầm uất, nhờ phong cách độc đáo và sinh hoạt tự do nên ngày nay rất được khách hàng ưa chuộng săn đón.",
    "他顾不上长途飞行的疲惫，稍稍歇息后就马不停蹄地与客户商讨合作事宜。": "Anh ấy chẳng màng tới sự mệt mỏi sau chuyến bay dài, chỉ chợp mắt nghỉ ngơi đôi chút rồi lại hối hả bàn bạc chuyện hợp tác với khách hàng.",
    "她坐在那里，低头摆弄着衣角，稍稍有些拘谨。": "Cô ấy ngồi ở đó, cúi đầu mân mê vạt áo, vẻ mặt thoáng chút e thẹn ngượng ngùng.",
    "按照赵医生的手术治疗方案，患者最后转危为安，家属对其万分感激。": "Theo phác đồ phẫu thuật của bác sĩ Triệu, bệnh nhân cuối cùng đã qua cơn nguy kịch, người nhà vô cùng cảm kích biết ơn ông.",
    "学生们平时只在银幕上见过周老师，现在有幸现场得见其“庐山真面目”，个个激动万分。": "Các học sinh ngày thường chỉ thấy thầy Chu qua màn ảnh, nay may mắn được tận mắt chiêm ngưỡng diện mạo đích thực của thầy tại hội trường, ai nấy đều xúc động khôn xiết.",
    "谈及自己的远大理想，他有点儿激动，面色微红，声音也有点儿颤抖。": "Khi nhắc tới lý tưởng cao xa của mình, anh ấy có phần xúc động, nét mặt hơi ửng hồng, giọng nói cũng thoáng chút run run.",
    "听了我的话，他微张着嘴，好像想说点儿什么，但最终还是什么也没说。": "Nghe xong lời tôi nói, anh ấy hơi hé miệng như muốn phân trần điều gì, nhưng rốt cuộc vẫn lặng thinh không nói.",
    "这次比赛中，9号选手的表现尤为突出，给评委和观众都留下了深刻的印象。": "Trong cuộc thi lần này, màn thể hiện của thí sinh số 9 đặc biệt nổi bật xuất sắc, để lại ấn tượng sâu đậm cho cả ban giám khảo lẫn khán giả.",
    "在三星堆考古新成果中，尤为引人注目的是一座通高近70厘米的大口尊。": "Trong các thành tựu khảo cổ mới tại di chỉ Tam Tinh Đôi, nổi bật thu hút sự chú ý nhất là một chiếc bình tôn miệng rộng cao gần 70 cm.",
    "随着年龄的增长和阅历的增加，他对父母的理解愈加深刻。": "Cùng với tuổi đời ngày một lớn và trải nghiệm sống dồi dào, sự thấu hiểu của anh ấy dành cho cha mẹ càng thêm sâu sắc hơn.",
    "在教练的精心指导下，她训练愈加刻苦，技术动作日臻完善。": "Dưới sự chỉ dẫn tận tình của huấn luyện viên, cô ấy luyện tập càng thêm khổ công, các động tác kỹ thuật ngày càng đạt tới độ hoàn hảo.",
    "离交稿的时间越近，作者的心情越发焦急。": "Thời hạn nộp bản thảo càng tới gần, tâm trạng của tác giả lại càng thêm sốt ruột bồn chồn.",
    "山路越走越陡峭，周围的雾气也越发浓重，我们不得不放慢了脚步。": "Đường núi càng đi càng dốc đứng, sương mù xung quanh cũng ngày một dày đặc hơn, chúng tôi buộc lòng phải bước chậm lại.",
    "在科技日新月异的今天，终身学习显得越发重要。": "Trong thời đại khoa học công nghệ đổi thay từng ngày như hiện nay, việc học tập suốt đời càng lộ rõ tầm quan trọng thiết yếu.",
    # 012
    "他向大家汇报了课题研究的总体思路，并在大体上描绘了下一步的行动方案。": "Anh ấy đã báo cáo với mọi người hướng tư duy tổng thể của đề tài nghiên cứu, đồng thời phác họa đại thể phương án hành động cho bước tiếp theo.",
    "中国古典园林所追求的，大体是“虽由人作，宛自天开”的境界。": "Cảnh giới mà các khu vườn hoa viên cổ điển Trung Hoa hướng tới đại khái chính là 'Tuy do bàn tay con người tạo dựng, mà ngỡ như cảnh sắc tự nhiên mở ra'.",
    "过去老北京逢年过节，街坊邻里互相拜年，这礼数是概不能免的。": "Xưa kia ở Bắc Kinh mỗi độ lễ tết, xóm giềng qua lại chúc tết lẫn nhau, cái lễ nghĩa này xưa nay tuyệt đối không thể bỏ qua.",
    "但凡参与本次竞赛并按要求提交作品者，概可获得纪念证书一份。": "Phàm là ai tham gia cuộc thi lần này và nộp tác phẩm đúng quy định thì thảy đều có thể nhận được một bản chứng nhận kỷ niệm.",
    "此次文化节以“传承与创新”为主题，展示了来自全国各地的百余件优秀手工艺品，皆为难得一见的佳作。": "Lễ hội văn hóa lần này lấy chủ đề 'Kế thừa và Đổi mới', trưng bày hơn 100 tác phẩm thủ công mỹ nghệ xuất sắc từ khắp cả nước, thảy đều là những tuyệt tác hiếm thấy.",
    "生活如同一面镜子，你对它笑，它也对你笑；你对它哭，它也对你哭。这皆是因果使然。": "Cuộc đời hệt như một tấm gương, bạn cười với nó nó sẽ mỉm cười lại với bạn; bạn khóc với nó nó cũng sẽ rơi lệ cùng bạn. Đó thảy đều do nhân quả tạo thành.",
    "由于工作原因，他们一家曾在多个城市居住过，但每到一处，尽皆能很快融入当地的生活。": "Do tính chất công việc, cả gia đình họ từng sinh sống qua nhiều thành phố, nhưng hễ tới bất cứ nơi đâu, toàn bộ mọi người đều có thể nhanh chóng hòa nhập vào nhịp sống bản địa.",
    "这首古琴曲曲调高雅，余音绕梁，尽显传统音乐的独特韵味。": "Bản nhạc cổ cầm này giai điệu thanh tao trang nhã, âm vang dội đọng lòng người, phô diễn trọn vẹn phong vị độc đáo của âm nhạc truyền thống.",
    "参与评选的五十位候选人均在各自的专业领域取得了卓越的成就。": "50 ứng viên tham gia đợt bình chọn đều đã gặt hái được những thành tựu vô cùng vượt bậc trong lĩnh vực chuyên môn của riêng mình.",
    "无论是在日常生活中还是在工作中，我们均应秉持实事求是的态度。": "Bất luận trong cuộc sống thường nhật hay trong công tác, chúng ta đều cần giữ vững thái độ cầu thị, tôn trọng sự thật.",
    "在突击检查中，该工厂因消防设施严重老化且未按要求配备灭火器，被通通勒令整改。": "Trong đợt kiểm tra đột xuất, nhà máy đó do hệ thống phòng cháy chữa cháy xuống cấp nghiêm trọng và không trang bị bình cứu hỏa theo chuẩn, nên toàn bộ đều bị yêu cầu đình chỉ để chấn chỉnh.",
    "在整理旧居时，他将多年积攒下来的旧报纸和各类杂物通通打包送到了废品回收站。": "Khi dọn dẹp căn nhà cũ, anh ấy gom hết toàn bộ đống báo cũ và các loại đồ đạc linh tinh tích cóp bấy lâu đem đóng gói gửi tới vựa phế liệu.",
    "无论遇到多大的困难，他统统独自承担，从不向朋友抱怨半句。": "Dẫu có vấp phải khó khăn lớn đến nhường nào, anh ấy tuốt tuồn tuột đều một mình gánh vác, chẳng bao giờ than vãn nửa lời với bạn bè.",
    "听到这个振奋人心的好消息，大家把所有的疲惫统统抛到了脑后。": "Nghe được tin mừng đầy phấn khởi này, mọi người đem toàn bộ những mỏi mệt quẳng sạch ra sau đầu.",
    "世间万物，唯变不变。唯有不断适应变化，才能在激烈的竞争中立于不败之地。": "Vạn vật trên đời, duy chỉ có sự biến đổi là không đổi. Chỉ có không ngừng thích nghi với đổi thay thì mới có thể đứng vững bất bại trong sự cạnh tranh khốc liệt.",
    "这座小岛与世隔绝，岛上居民出行，唯有一艘老旧的小木船可供渡江。": "Hòn đảo nhỏ này biệt lập với thế giới bên ngoài, cư dân trên đảo mỗi khi đi lại chỉ có duy nhất một con thuyền gỗ cũ kỹ để qua sông.",
    "参加此次高端论坛的专家学者多达数百人，唯独李教授因临时有紧急手术而未能出席。": "Các chuyên gia học giả tham dự diễn đàn cao cấp lần này lên tới hàng trăm người, duy chỉ có giáo sư Lý vì có ca phẫu thuật khẩn cấp đột xuất nên không thể đến dự.",
    "全班四十位同学，唯独他一人自始至终坚持每天晨跑，从未间断。": "Cả lớp 40 bạn học, duy chỉ có mình cậu ấy là trước sau kiên trì chạy bộ sáng mỗi ngày, chưa từng ngơi nghỉ một buổi nào.",
    "面对这次看似不可逆转的危机，唯有背水一战，方有一线生机。": "Đứng trước cuộc khủng hoảng tưởng chừng không thể vãn hồi này, chỉ có duy nhất một cách là dốc toàn lực quyết chiến đến cùng thì mới mong có một tia hy vọng.",
    "要想彻底掌握一门语言，唯有沉浸于该语言的文化语境之中，多听、多说、多练。": "Muốn nắm vững triệt để một ngôn ngữ, con đường duy nhất là đắm mình vào ngữ cảnh văn hóa của ngôn ngữ đó, chịu khó nghe nhiều, nói nhiều và luyện tập thật nhiều.",
    "这篇长篇大论看似立意高远，言辞华丽，其实无非是老调重弹，毫无实质性的新见解。": "Bài viết dài dòng văn tự này trông thì có vẻ tầm nhìn cao xa, câu từ hoa mỹ, nhưng thực chất chẳng qua chỉ là nhai lại điệp khúc cũ, chẳng có một chút kiến giải mới mẻ nào.",
    "他之所以每天这么拼命地工作，无非是想给家人创造一个更加稳定舒适的生活环境。": "Sở dĩ anh ấy ngày nào cũng làm việc bạt mạng đến thế, chẳng qua cũng chỉ vì muốn tạo dựng cho gia đình một mái ấm ổn định và sung túc hơn.",
    "对于一切弄虚作假、学术不端的行为，学校学术委员会态度鲜明，一概予以严惩，决不姑息。": "Đối với tất cả các hành vi gian lận dối trá, vi phạm liêm chính học thuật, Hội đồng học thuật nhà trường giữ lập trường rõ ràng: hoàn toàn xử lý nghiêm khắc không khoan nhượng.",
    "凡未经官方授权许可而在网络上非法传播该电影资源的行为，版权方将一概追究其法律责任。": "Phàm mọi hành vi phát tán trái phép nguồn phim này trên mạng internet mà không có văn bản ủy quyền chính thức, phía nắm bản quyền sẽ truy cứu trách nhiệm pháp lý tới cùng.",
    "凡因个人原因未能在规定时间内完成报名注册者，逾期一概不予补办。": "Phàm những ai vì lý do cá nhân mà không hoàn thành thủ tục đăng ký trong thời hạn quy định, quá hạn đều sẽ tuyệt đối không giải quyết bổ sung.",
    # 013
    "这个问题相当复杂，各方意见分歧很大，我们姑且搁置争议，先讨论那些容易达成共识的条款。": "Vấn đề này tương đối phức tạp, bất đồng ý kiến giữa các bên rất lớn, chúng ta tạm thời gác lại tranh cãi, trước tiên hãy bàn về các điều khoản dễ đạt được sự đồng thuận.",
    "对于外界的种种不实猜测，当事人姑且付之一笑，并未急于出面辩解。": "Đối với muôn vàn lời đồn đoán sai sự thật từ bên ngoài, người trong cuộc chỉ tạm mỉm cười cho qua chuyện chứ không hề vội vã ra mặt thanh minh.",
    "合同一经双方签字盖章，即告生效，具有法律约束力。": "Hợp đồng một khi đã được hai bên ký tên đóng dấu là lập tức có hiệu lực và mang tính ràng buộc pháp lý.",
    "该产品在市场上即买即走，极大地节省了消费者的结算时间。": "Sản phẩm này trên thị trường mua xong là mang đi ngay, giúp tiết kiệm tối đa thời gian thanh toán của người tiêu dùng.",
    "在智慧课堂中，李老师通过平板电脑向学生发布任务，根据平台精准反馈的学情即时进行教学调整。": "Trong lớp học thông minh, thầy Lý giao bài tập cho học sinh qua máy tính bảng, căn cứ theo dữ liệu phản hồi chuẩn xác trên hệ thống để kịp thời điều chỉnh việc giảng dạy ngay tức khắc.",
    "线上支付系统在交易完成后，会即时向用户的手机发送消费短信提醒，确保资金安全。": "Hệ thống thanh toán trực tuyến sau khi hoàn tất giao dịch sẽ gửi ngay tin nhắn thông báo trừ tiền về điện thoại người dùng, bảo đảm an toàn dòng tiền.",
    "本次国际研讨会定于下月十五日在北京开幕，届时将有来自三十多个国家的顶级专家齐聚一堂。": "Hội thảo quốc tế lần này ấn định khai mạc vào ngày 15 tháng tới tại Bắc Kinh, đến thời điểm đó sẽ có các chuyên gia hàng đầu đến từ hơn 30 quốc gia tề tựu đông đủ.",
    "新校区二期工程预计年底前竣工，届时全校师生将享受到更加宽敞现代的教学科研空间。": "Công trình giai đoạn hai của cơ sở mới dự kiến hoàn thành trước cuối năm, đến lúc đó toàn thể thầy trò sẽ được thụ hưởng không gian học tập và nghiên cứu khang trang hiện đại hơn.",
    "为了不耽误后续审批进度，请各位申请人尽早备齐相关材料并提交审核。": "Để không làm chậm trễ tiến độ phê duyệt tiếp theo, kính đề nghị các ứng viên chuẩn bị đầy đủ hồ sơ liên quan và nộp duyệt càng sớm càng tốt.",
    "如有任何异议，请在公示期内尽早向监察部门提出书面申诉。": "Nếu có bất kỳ khiếu nại nào, xin vui lòng gửi đơn khiếu nại bằng văn bản tới bộ phận thanh tra càng sớm càng tốt trong thời hạn công khai.",
    "双方经过多轮艰苦磋商，始终无法在核心利益上达成妥协，合作谈判就此破裂。": "Hai bên sau nhiều vòng thương lượng gian nan vẫn không thể dung hòa thỏa hiệp về mặt lợi ích cốt lõi, cuộc đàm phán hợp tác từ đây chính thức đổ vỡ.",
    "原本热闹非凡的古老集镇，随着现代交通枢纽的转移，就此逐渐走向了衰落。": "Khu chợ cổ sầm uất năm nào, cùng với việc dịch chuyển của các đầu mối giao thông hiện đại, từ đó dần dần chìm vào cảnh hoang tàn suy vi.",
    "中华民族历来是一个爱好和平的民族，睦邻友好、讲信修睦是深入骨髓的文化基因。": "Dân tộc Trung Hoa từ xưa đến nay luôn là một dân tộc yêu chuộng hòa bình; hữu nghị láng giềng, trọng chữ tín là gen văn hóa ăn sâu vào tận xương tủy.",
    "这所百年名校历来注重培养学生的独立思考能力与批判性思维。": "Ngôi trường danh tiếng trăm năm này từ trước đến nay luôn chú trọng rèn luyện năng lực tư duy độc lập và tư duy phản biện cho học sinh.",
    "关于该遗址的最初年代判定，学术界尚存在诸多争论，需要更充分的考古发掘证据。": "Về việc xác định niên đại sơ khởi của di chỉ này, giới học thuật vẫn còn tồn tại rất nhiều tranh cãi, cần thêm những chứng cứ khảo cổ đầy đủ hơn.",
    "工程虽然已经顺利封顶，但内部管线铺设与精密仪器安装尚需数月方能完成。": "Công trình tuy đã cất nóc thuận lợi, nhưng việc lắp đặt đường ống nội bộ và thiết bị đo đạc chuẩn xác vẫn còn cần vài tháng nữa mới có thể hoàn tất.",
    "发言人宣读完声明后，随即回答了在场中外媒体记者的几个热点问题。": "Người phát ngôn sau khi đọc xong bản tuyên bố liền ngay sau đó trả lời một số câu hỏi nóng của các phóng viên truyền thông trong và ngoài nước.",
    "大雨骤停，天空中随即出现了一道色彩斑斓的彩虹，引得游人纷纷拍照留念。": "Cơn mưa rào vừa dứt, trên nền trời ngay tức khắc xuất hiện một dải cầu vồng rực rỡ sắc màu, khiến du khách đua nhau chụp ảnh kỷ niệm.",
    "他向来行事低调稳重，很少在公开场合高谈阔论。": "Anh ấy từ trước tới nay làm việc luôn khiêm nhường cẩn trọng, rất ít khi phát biểu đao to búa lớn ở nơi công cộng.",
    "南方沿海地区夏季向来多台风暴雨，当地居民早已积累了丰富的防汛防台经验。": "Vùng duyên hải phương nam vào mùa hè từ xưa tới nay vốn hay có bão lũ mưa dông, người dân nơi đây từ lâu đã tích lũy được nhiều kinh nghiệm chống bão phong phú.",
    "该项技术专利一经发布，便引起了全球同行业领军企业的高度关注与激烈竞标。": "Bằng sáng chế kỹ thuật này một khi vừa công bố đã lập tức thu hút sự quan tâm đặc biệt và màn đấu thầu gay cấn của các doanh nghiệp đầu ngành toàn cầu.",
    "新修订的法律条文一经全国人大常委会表决通过，即自公布之日起正式施行。": "Các điều khoản luật mới sửa đổi một khi được Ủy ban Thường vụ Đại hội Đại biểu Nhân dân Toàn quốc biểu quyết thông qua là chính thức có hiệu lực kể từ ngày công bố.",
    "天色已晚，山路崎岖难行，我们暂且在山脚下的客栈歇脚一晚，明日破晓再行登山。": "Trời đã về chiều, đường núi gập ghềnh khó đi, chúng ta tạm thời nghỉ chân một đêm ở quán trọ dưới chân núi, chờ sáng mai tinh mơ rạng đông rồi hẵng tiếp tục leo núi.",
    "由于关键数据尚未汇总完毕，该报告的定稿工作暂且顺延至下周进行。": "Do các số liệu the chốt vẫn chưa tổng hợp xong xuôi, nên công tác hoàn thiện bản báo cáo cuối cùng tạm thời dời lại sang tuần sau.",
    "希望广大青年学子珍惜韶华，刻苦钻研，早日成长为堪当民族复兴大任的栋梁之材。": "Hy vọng đông đảo các bạn thanh niên học sinh biết trân quý năm tháng thanh xuân, miệt mài nghiên cứu, sớm ngày trưởng thành thành rường cột gánh vác sứ mệnh phục hưng dân tộc.",
    "经过医护人员的全力救治与悉心照料，多位重症患者病情趋于平稳，有望早日康复出院。": "Nhờ sự cứu chữa hết lòng và chăm sóc tận tụy của đội ngũ y bác sĩ, nhiều bệnh nhân nặng đã chuyển biến ổn định, có hy vọng sớm ngày bình phục xuất viện.",
    # 014
    "老艺术家的精湛演出博得了全场观众的连连掌声与喝彩。": "Màn trình diễn điêu luyện tuyệt đỉnh của người nghệ sĩ lão thành đã giành được những tràng pháo tay tán thưởng và tiếng reo hò không ngớt từ toàn thể khán giả.",
    "在激烈的辩论赛中，他逻辑严密，引经据典，令对手连连点头称赞。": "Trong trận tranh biện nảy lửa, anh ấy lập luận chặt chẽ, dẫn kinh điểm tích, khiến đối thủ cũng phải liên hồi gật đầu khâm phục.",
    "尽管有关部门屡次下发安全整改通知，该企业依然我行我素，最终酿成了严重火灾。": "Dẫu cho các cơ quan chức năng năm lần bảy lượt gửi công văn yêu cầu chấn chỉnh an toàn, xí nghiệp này vẫn chứng nào tật nấy, cuối cùng đã dẫn tới trận hỏa hoạn nghiêm trọng.",
    "他在求职过程中屡次碰壁，但始终没有丧失对未来的信心与勇气。": "Trên con đường tìm kiếm việc làm anh ấy đã liên tiếp vấp phải trắc trở, nhưng chưa bao giờ đánh mất niềm tin và dũng khí hướng tới tương lai.",
    "近几年来，极端恶劣天气在世界各地屡屡出现，给全球生态环境敲响了警钟。": "Vài năm trở lại đây, các hình thái thời tiết cực đoan nguy hiểm liên tiếp xuất hiện ở khắp nơi trên thế giới, gióng lên hồi chuông cảnh báo cho môi trường sinh thái toàn cầu.",
    "在国际大赛舞台上，中国年轻选手屡屡斩获金牌，展现了新一代青年的朝气与风采。": "Trên đấu trường quốc tế, các vận động viên trẻ tuổi Trung Quốc liên tục rinh về các tấm huy chương vàng, thể hiện trọn vẹn khí thế và bản lĩnh của thế hệ trẻ thời đại mới.",
    "近年来两国外交摩擦频发，经贸往来与民间人文交流均受到了不同程度的负面影响。": "Những năm gần đây va chạm ngoại giao giữa hai nước diễn ra dồn dập, khiến giao lưu kinh tế thương mại và văn hóa nhân văn đều chịu ảnh hưởng tiêu cực ở các mức độ khác nhau.",
    "该学术期刊因频出高质量的前沿研究成果，在国际学术界的引用率与影响力持续飙升。": "Tạp chí học thuật này nhờ liên tục cho ra đời những công trình nghiên cứu tiên phong chất lượng cao, nên tỷ lệ trích dẫn và tầm ảnh hưởng trên trường quốc tế không ngừng tăng vọt.",
    "初春的天气变幻莫测，时而阳光普照，暖意融融；时而阴雨连绵，寒风刺骨。": "Thời tiết đầu xuân biến ảo khôn lường, lúc thì ngập tràn ánh nắng ấm áp dịu dàng, lúc lại mưa phùn rả rích gió rét buốt căm căm.",
    "在漫长的创作生涯中，他时而激情澎湃，文思如泉涌；时而陷入苦思，数月难落一字。": "Trong suốt sự nghiệp sáng tác dài đằng đẵng, ông lúc thì sục sôi nhiệt huyết văn tứ tuôn trào như suối, khi lại rơi vào bế tắc đăm chiêu suốt mấy tháng trời chẳng viết nổi một chữ.",
    "作为一名医务工作者，救死扶伤的崇高使命时时萦绕在他的心头。": "Là một cán bộ nhân viên y tế, sứ mệnh cứu người cao cả luôn luôn thường trực văng vẳng trong tâm khảm của anh.",
    "出门在外，母亲的殷切叮咛与关怀时时温暖着游子的心灵。": "Những ngày bươn chải nơi đất khách, lời dặn dò ân cần và sự quan tâm của mẹ luôn sưởi ấm tâm hồn người con xa xứ.",
    "随着国内疫情防控政策的优化调整，多项支持经济平稳发展的利好政策相继出台落地。": "Cùng với việc tối ưu hóa điều chỉnh chính sách phòng chống dịch bệnh trong nước, nhiều gói chính sách hỗ trợ phát triển kinh tế bền vững đã lần lượt được ban hành và đi vào thực tiễn.",
    "自上世纪末以来，这所乡村中学相继走出了数十位博士生和国家级拔尖人才。": "Kể từ cuối thế kỷ trước đến nay, ngôi trường trung học làng quê này đã lần lượt chắp cánh cho hàng chục tiến sĩ và nhân tài kiệt xuất cấp quốc gia.",
    "听到这个天大的喜讯，他高兴得手舞足蹈，一个劲儿地拉着朋友的手傻笑。": "Nghe được tin vui trời cho này, anh ấy mừng rỡ nhảy cẫng lên, cứ nắm chặt lấy tay bạn cười tít mắt không ngừng.",
    "会议进行中，后排的几位听众却一个劲儿地低头刷手机，毫无听讲之意。": "Cuộc họp đang diễn ra nghiêm túc, thế nhưng mấy vị khán giả ở hàng ghế sau cứ cắm đầu cắm cổ lướt điện thoại, chẳng có chút ý tứ lắng nghe nào.",
    "受持续强降雨天气影响，南方某省一连五天发布暴雨红色预警信号。": "Chịu ảnh hưởng của đợt mưa lớn kéo dài, một tỉnh miền nam đã liền tù tì 5 ngày phát tín hiệu cảnh báo mưa bão cấp độ đỏ.",
    "为了攻克这个技术难关，科研团队一连奋战了三个昼夜，最终取得了突破性进展。": "Để vượt qua nút thắt kỹ thuật này, đội ngũ nghiên cứu đã thức trắng liền 3 ngày 3 đêm chiến đấu, cuối cùng đã giành được bước tiến mang tính đột phá.",
    "在阔别赛场两年之后，这位老将再度披挂上阵，并在决赛中顽强拼搏，勇夺桂冠。": "Sau 2 năm xa rời sàn đấu, vị lão tướng này đã lại một lần nữa tái xuất, thi đấu kiên cường ngoan cường trong trận chung kết và xuất sắc đoạt ngôi quán quân.",
    "该作家推出的最新长篇历史小说，再度引发了广大读者与文艺评论界的热烈探讨。": "Bộ tiểu thuyết lịch sử dài tập mới nhất của nhà văn này lại một lần nữa dấy lên làn sóng thảo luận sôi nổi trong đông đảo độc giả và giới phê bình văn nghệ."
}
