# -*- coding: utf-8 -*-
"""
HSK 7-9 Grammar - Part 1B: Items 015 - 024 (129 sentences)
Phó từ phương thức, Phủ định, Ngữ khí, Phán đoán, Giới từ, Liên từ, Trợ từ văn ngôn.
"""

METADATA_1B = [
    {
        "order": 15,
        "titleVi": "Chùm phó từ phương thức & hành động chuẩn mực HSK 7-9 (36 từ)",
        "structure": "Phó từ phương thức + Động từ",
        "category": "cau-tu-tu-loai",
        "explanation": "Hệ thống phó từ phương thức miêu tả hành vi cực kỳ phong phú và tinh tế: '按理' / '按说' (theo lý lẽ/thông thường mà nói); '百般' (trăm phương ngàn kế, hết mực cưng chiều/mài giũa); '不由得' (bất giác, không kìm được); '趁机' / '趁早' (nhân cơ hội / nhân lúc còn sớm); '大肆' (thẳng tay, ra sức bừa bãi); '断然' (dứt khoát, kiên quyết); '公然' (công khai, ngang nhiên); '火速' (hỏa tốc, khẩn cấp); '截然' (hoàn toàn tách biệt - 截然相反); '竭力' (dốc hết sức lực); '尽情' (thỏa thích, hết mình); '就近' (tiện thể gần đó); '刻意' (cố tình, dụng tâm); '拼命' (liều mạng, bạt mạng); '强行' (cưỡng chế, ép buộc); '任意' (tùy tiện, tùy ý); '日趋' (ngày một có xu hướng); '如期' (đúng kỳ hạn); '擅自' / '私自' (tự tiện, lén lút làm trái phép); '特此' (nay đặc biệt... - dùng trong công văn: 特此通知); '瞎' (bừa bãi, mù quáng); '一并' (nhân tiện cùng lúc - gộp chung); '一举' (một cú, một phen thắng lợi); '一手' (tự tay mình gây ra/gây dựng); '毅然' (kiên quyết, dứt khoát hy sinh); '有意' (cố ý, có ý định); '照常' / '照例' / '照样' (như thường lệ, vẫn y như cũ); '执意' (khăng khăng, cố chấp); '骤然' (đột ngột, bất thình lình); '逐一' (từng cái một, lần lượt); '专程' (cất công lặn lội vì một mục đích).",
        "tips": "Đây là nhóm từ xuất hiện với mật độ cao nhất trong các bài văn xuôi nghệ thuật và bài luận nghị luận xã hội HSK 7-9."
    },
    {
        "order": 16,
        "titleVi": "Chùm phó từ phủ định văn ngôn & trang trọng: 不见得, 绝不, 无从, 无须, 无可, 勿",
        "structure": "Phó từ phủ định + Vị ngữ",
        "category": "cau-tu-tu-loai",
        "explanation": "Phủ định đa tầng nấc mang tính học thuật: '不见得' (chưa chắc đã); '绝不' (tuyệt đối không); '无从' (không có cách nào, không biết bắt đầu từ đâu - 无从说起, 无从得知); '无须' (không cần thiết phải - bằng 不必); '无可' (không thể nào... nổi - 无可指摘, 无可奉告); '勿' (chớ, đừng - văn ngôn pháp lý: 切勿, 请勿, 勿念).",
        "tips": "Cụm '无可奉告' (miễn bình luận/không có gì để thông báo) là câu nói kinh điển trong phỏng vấn báo chí và ngoại giao."
    },
    {
        "order": 17,
        "titleVi": "Hệ thống phó từ ngữ khí biểu cảm & phản biện tri thức HSK 7-9 (33 từ)",
        "structure": "Chủ ngữ + Phó từ ngữ khí + Vị ngữ",
        "category": "cau-tu-tu-loai",
        "explanation": "Chùm phó từ biểu cảm và lập luận sắc bén: '必定' / '必将' (nhất định, tất sẽ); '不妨' (thiết nghĩ cũng chẳng sao, thử xem sao); '不免' (khó tránh khỏi); '反倒' (trái lại còn); '非得...不可' (nhất định phải... mới chịu); '分明' (rõ rành rành); '怪不得' / '难怪' (thảo nào, hèn chi); '果真' (quả nhiên); '好在' / '幸好' / '幸亏' (may mà, may nhờ có); '何必' / '何苦' (hà tất, việc gì phải khổ sở vậy); '竟' / '愣' (thế mà, vậy mà - ngoài sức tưởng tượng); '莫非' (chẳng lẽ, hay là); '宁可' / '宁愿' / '情愿' (thà rằng, thà là); '碰巧' / '恰巧' (vừa khéo, tình cờ trùng hợp); '偏偏' (oái oăm thay, cứ nhất quyết); '切' (nhất thiết phải - 切记, 切不可); '势必' (tất yếu sẽ dẫn đến); '索性' (dứt khoát, chi bằng); '万万' (vạn lần tuyệt đối không - 万万不可); '未免' (e rằng hơi quá, khó tránh); '务必' (nhất định phải); '终究' (rốt cuộc trước sau vẫn); '何不' (sao không); '何尝' (nào có phải, dễ gì đã).",
        "tips": "Nắm vững nhóm từ này giúp bài luận phân tích luận điểm đạt độ đanh thép, tinh tế và giàu cảm xúc trí tuệ."
    },
    {
        "order": 18,
        "titleVi": "Phó từ phán đoán khẳng định văn ngôn: 乃 (nǎi - chính là, quả là)",
        "structure": "Chủ ngữ + 乃 + Danh từ / Cụm vị ngữ",
        "category": "cau-tu-tu-loai",
        "explanation": "'乃' (nǎi) là hư từ gốc Hán cổ thay thế cho '是' (chính là, quả đúng là) hoặc dùng làm đại từ 'đó là'. Thường dùng trong các câu đúc kết mang tính châm ngôn, ca ngợi nghệ thuật hoặc câu khẩu ngữ quen thuộc ('真乃佳作' - quả là tuyệt tác; '此乃天机' - đây là thiên cơ).",
        "tips": "Xuất hiện nhiều trong các câu trích dẫn văn học cổ, lời bình phẩm thư họa và ngữ cảnh đối thoại uyên thâm."
    },
    {
        "order": 19,
        "titleVi": "Giới từ khẩu ngữ khởi điểm không gian & thời gian: 打 (dǎ - từ, kể từ)",
        "structure": "打 + Mốc thời gian / Nơi chốn + Động từ",
        "category": "cau-tu-tu-loai",
        "explanation": "'打' làm giới từ tương đương với '从' (từ, xuất phát từ), mang đậm sắc thái khẩu ngữ miền Bắc và phương ngữ đời sống ('打这天起' - kể từ ngày này trở đi; '打皇宫里流出来' - từ trong hoàng cung tuồn ra).",
        "tips": "Tránh nhầm với động từ 'đánh' (打); khi làm giới từ, sau '打' luôn là danh từ thời gian hoặc địa điểm."
    },
    {
        "order": 20,
        "titleVi": "Giới từ dẫn xuất bối cảnh & chủ đề: 当着 (trước mặt), 就 (về, đối với)",
        "structure": "当着 + Ai / Mọi người + Động từ  ||  就 + Vấn đề / Chủ đề + Động từ thảo luận",
        "category": "cau-tu-tu-loai",
        "explanation": "'当着' (dāngzhe) biểu thị hành động diễn ra công khai ngay trước mặt đối phương hoặc chốn đông người; '就' làm giới từ tương đương '关于, 对于' dẫn xuất chủ đề, tranh chấp hoặc đề tài thảo luận trong hội nghị cấp cao.",
        "tips": "Trong văn bản ngoại giao: '就...交换了意见' (đã trao đổi ý kiến về vấn đề...)."
    },
    {
        "order": 21,
        "titleVi": "Hệ thống giới từ căn cứ pháp lý & tiến trình: 本着, 基于, 鉴于, 经, 依",
        "structure": "本着 / 基于 / 鉴于 / 经 / 依 + Căn cứ / Nguyên tắc + Vị ngữ",
        "category": "cau-tu-tu-loai",
        "explanation": "Chùm giới từ căn cứ hành chính: '本着' (dựa trên tinh thần/nguyên tắc); '基于' (dựa trên cơ sở thực tiễn/sự kiện có thật); '鉴于' (xét thấy tình hình/xét đến thành tích); '经' (qua quá trình điều tra/nghiên cứu/phê chuẩn: 经批准, 经研究, 经诊治); '依' (theo, căn cứ vào ý kiến: 依我看 - theo tôi thấy).",
        "tips": "Mở đầu các quyết định khen thưởng, kỷ luật, bổ nhiệm công chức luôn bắt đầu bằng '鉴于...' hoặc '经研究决定...'."
    },
    {
        "order": 22,
        "titleVi": "Liên từ nối phân câu giả thiết, bổ sung & dự phòng: 况且, 免得, 若, 倘若, 以防, 鉴于",
        "structure": "Phân câu 1，况且 / 免得 / 若 / 倘若 / 以防 / 鉴于 + Phân câu 2",
        "category": "cau-tu-tu-loai",
        "explanation": "Liên từ liên kết phân câu logic: '鉴于' (xét thấy lý do ở vế trước); '况且' (hơn nữa, vả lại - bổ sung thêm một lý do có sức nặng); '免得' (để tránh, kẻo lại sinh chuyện); '若' / '倘若' (nếu, giả sử như - văn viết thanh tao); '以防' (nhằm đề phòng, phòng ngừa rủi ro xấu).",
        "tips": "'以防' thường đứng trước kết quả tiêu cực tiềm ẩn (以防上当受骗 - để tránh bị lừa)."
    },
    {
        "order": 23,
        "titleVi": "Liên từ tăng tiến & song hành trang trọng: 加之, 乃至, 且",
        "structure": "A，加之 B，使得...  ||  A，乃至 B  ||  A 且 B",
        "category": "cau-tu-tu-loai",
        "explanation": "'加之' (thêm vào đó, cộng thêm - nêu lý do phụ trợ đẩy nhanh kết quả); '乃至' (cho đến, thậm chí đến mức - nối các vế tăng tiến theo cấp số nhân: 数月乃至一年); '且' (và, hơn nữa - nối hai tính từ hoặc phân câu pháp lý: 吊销驾照且终身禁驾).",
        "tips": "'乃至' biểu thị mức độ cực hạn cao hơn nhiều so với '甚至'."
    },
    {
        "order": 24,
        "titleVi": "Trợ từ ngữ khí văn ngôn cổ điển: 罢了, 也罢, 矣",
        "structure": "Cuối câu + 罢了 / 也罢 / 矣",
        "category": "cau-tu-tu-loai",
        "explanation": "Trợ từ sắc thái biểu cảm đậm chất Hán học: '罢了' (mà thôi, chẳng qua chỉ là); '也罢' (cũng được, đành vậy / A也好B也罢); '矣' (yǐ - trợ từ cảm thán văn ngôn tương đương 了: '足矣' - đủ rồi vậy; '仰慕久矣' - ngưỡng mộ đã lâu năm vậy).",
        "tips": "Câu danh ngôn kết thúc bằng '足矣' (được một tri kỷ trên đời thế là đủ mãn nguyện rồi)."
    }
]

TRANSLATIONS_1B = {
    # 015
    "按理，一到广州我就应该即刻去拜访先生，不料因行程繁忙到最后也未能成行。": "Theo lẽ thường, vừa đặt chân đến Quảng Châu là tôi phải lập tức tới bái kiến thầy, chẳng ngờ do lịch trình quá bận rộn nên mãi tới tận phút chót vẫn không thể lên đường ghé thăm.",
    "你出现了这个失误，按理该扣一个月的工资，但看在你平时工作还算认真的份上，公司决定给你机会将功补过。": "Bạn đã để xảy ra sơ suất này, theo lẽ đáng ra phải trừ một tháng lương, nhưng nể tình ngày thường bạn làm việc khá chăm chỉ, công ty quyết định cho bạn cơ hội lập công chuộc tội.",
    "按说，以方平的能力完全可以在大城市里立足，可他为了方便照顾父母，毅然选择回乡工作。": "Theo lý mà nói, với năng lực của Phương Bình hoàn toàn có thể lập nghiệp đứng vững ở các thành phố lớn, nhưng để tiện bề chăm sóc bố mẹ, anh ấy đã kiên quyết chọn về quê làm việc.",
    "年轻人的私事，按说我不该多问，可是既然影响到了工作，我就不能不问一问了。": "Chuyện đời tư của người trẻ, theo lý lẽ thì tôi không nên can thiệp hỏi han nhiều, nhưng một khi đã ảnh hưởng trực tiếp tới công việc chung thì tôi buộc lòng phải lên tiếng nhắc nhở.",
    "养护工人对园内种植的一草一木百般呵护，定时浇水、悉心修剪。": "Những người công nhân chăm sóc vườn tược hết mực nâng niu từng nhành cây ngọn cỏ trong khuôn viên, đúng giờ tưới nước và cẩn thận tỉa cành.",
    "这部作品经过了作者的反复斟酌、百般打磨，一经发表便好评如潮。": "Tác phẩm này đã trải qua muôn phen đắn đo cân nhắc và gọt giũa trăm bề của tác giả, vừa mới phát hành đã lập tức đón nhận cơn mưa lời khen từ công chúng.",
    "看见前面登场的选手纷纷取得了较高的得分，即将表演的白兰不由得紧张了起来。": "Thấy các thí sinh bước lên sân khấu trước đó đều liên tiếp đạt điểm số rất cao, Bạch Lan chuẩn bị biểu diễn bất giác cảm thấy vô cùng hồi hộp căng thẳng.",
    "看到新戏排练终于有了进展，导演不由得松了口气。": "Nhìn thấy việc tập dượt vở kịch mới cuối cùng cũng có được bước tiến triển, vị đạo diễn bất giác thở phào nhẹ nhõm.",
    "对方球员心情焦躁，失误明显增多，黑龙江队趁机将比分反超。": "Các cầu thủ đội bạn tâm lý nóng vội bồn chồn, sai lầm lộ rõ tăng lên, đội Hắc Long Giang nhân cơ hội đó đã vươn lên dẫn ngược điểm số.",
    "全套课程系统讲授了深度学习的常用算法，并非无良商家在人工智能风口趁机推出的“割韭菜”产品。": "Toàn bộ khóa học giảng dạy một cách có hệ thống các thuật toán học sâu thông dụng, tuyệt nhiên không phải là loại sản phẩm trục lợi lừa đảo do những thương gia bất chính nhân làn sóng trí tuệ nhân tạo tung ra.",
    "8号球员好像不在状态，刚才又受了伤，趁早把他换下来，以免影响比赛结果。": "Cầu thủ số 8 dường như đang không có được phong độ tốt, vừa nãy lại dính chấn thương, chi bằng nhân lúc sớm hãy thay cậu ấy ra để tránh ảnh hưởng tới cục diện trận đấu.",
    "你想靠炒股票赚钱？趁早打消这个念头儿吧，你别听人忽悠，炒股的人没有几个赚钱的。": "Cậu muốn kiếm tiền bằng việc chơi chứng khoán sao? Mau sớm dẹp ngay cái ý định viển vông đó đi, đừng nghe người ta vẽ hươu vẽ vượn, người đầu tư cổ phiếu chẳng mấy ai kiếm được đồng lời đâu.",
    "他在饭桌上大肆吹嘘自己的财富和人脉，试图建立起一个成功人士的形象。": "Hắn ta trên bàn ăn ra sức huênh hoang khoác lác về khối tài sản và những mối quan hệ rộng lớn của mình hòng tạo dựng hình ảnh một người đàn ông thành đạt.",
    "夏季是害虫大肆为害的时节，为保障群众身心健康，服务团队对重点区域进行了全方位的科学消杀。": "Mùa hè là thời điểm sâu bệnh hoành hành tác oai tác quái, để bảo đảm an toàn sức khỏe cho người dân, đội ngũ phục vụ đã tiến hành phun thuốc khử khuẩn khoa học toàn diện tại các vùng trọng điểm.",
    "对于贵方提出的无理要求，我方断然拒绝。": "Đối với những yêu sách vô lý do quý vị đưa ra, phía chúng tôi kiên quyết từ chối một cách dứt khoát.",
    "举办一场国际展览会，断然不可能仅凭一己之力完成，需各方精诚合作、共同努力。": "Việc tổ chức một hội chợ triển lãm quốc tế dứt khoát không thể nào chỉ trông chờ vào sức lực đơn độc của một cá nhân, mà đòi hỏi các bên phải chân thành hợp tác và dốc lòng chung tay.",
    "被告公然违反法律规定，散布谣言，严重损害了原告的商业信誉。": "Bị cáo đã ngang nhiên vi phạm các quy định của pháp luật, tung tin đồn thất thiệt, gây tổn hại nghiêm trọng tới uy tín thương mại của nguyên đơn.",
    "他在训练时公然顶撞主教练，受到严肃批评是理所当然的。": "Cậu ta trong buổi tập dám công khai chống đối cãi lại huấn luyện viên trưởng, việc bị phê bình nghiêm khắc kiểm điểm là lẽ đương nhiên.",
    "地震发生后，他主动终止休假，火速归队，毅然投身抢险救灾第一线。": "Sau khi trận động đất xảy ra, anh ấy đã chủ động chấm dứt kỳ nghỉ phép, hỏa tốc trở về đơn vị và kiên quyết lao ngay vào tuyến đầu cứu hộ cứu nạn.",
    "高速公路上一辆大货车轮胎起火亟需救援，高速交警接警后，火速派附近警力和119消防车前往现场救援。": "Trên đường cao tốc có một chiếc xe tải lớn bốc cháy lốp xe đang nguy cấp cần ứng cứu, lực lượng cảnh sát giao thông sau khi nhận tin báo đã hỏa tốc điều động lực lượng cảnh sát gần nhất cùng xe chữa cháy 119 tức tốc tới hiện trường giải cứu.",
    "他们俩虽是双胞胎，性格却截然相反。": "Hai đứa bọn họ tuy là anh em sinh đôi cùng một bọc, nhưng tính cách thì lại hoàn toàn trái ngược nhau một trời một vực.",
    "供给和需求好比一枚硬币的两面，无法截然分开。": "Cung và cầu hệt như hai mặt của cùng một đồng tiền, tuyệt đối không thể nào tách bạch ra làm đôi.",
    "匠人们非常注重技法的精湛，竭力使自己的作品成为流传千古的艺术精品。": "Những người thợ thủ công hết sức chú trọng sự tinh xảo điêu luyện của kỹ pháp, dốc cạn tâm huyết để tác phẩm của mình trở thành kiệt tác nghệ thuật lưu danh thiên cổ.",
    "但凡旅客有需求，小到一针一线，大到轮椅担架，铁路工作人员都会竭力满足。": "Phàm hễ hành khách có nhu cầu, nhỏ từ chiếc kim sợi chỉ cho đến to như xe lăn cáng cứu thương, nhân viên ngành đường sắt đều dốc lòng phục vụ chu đáo.",
    "游客们迫不及待地躺在草地上尽情呼吸新鲜的空气，享受灿烂的阳光。": "Các du khách háo hức ngả lưng trên thảm cỏ xanh mướt, thỏa sức hít thở bầu không khí trong lành và tận hưởng ánh nắng vàng rực rỡ.",
    "在壬寅虎年来临之际，各地人民以丰富多彩的活动，尽情表达了他们的喜悦之情和对新一年的美好憧憬。": "Nhân dịp Tết Nhâm Dần cận kề, nhân dân khắp nơi thông qua các hoạt động muôn màu muôn vẻ đã thỏa lòng bày tỏ niềm hân hoan cùng niềm ước vọng tươi đẹp về một năm mới an khang.",
    "所谓“就近入学”，一般是按照户口所在地去附近的学校登记入学。": "Cái gọi là 'nhập học theo tuyến gần nhà' thông thường là căn cứ theo nơi đăng ký hộ khẩu để ghi danh học tại ngôi trường gần nhất.",
    "过去驾驶证补换需前往车管所办理，现在在网上提交信息后即可就近领取。": "Trước đây việc cấp đổi giấy phép lái xe phải trực tiếp đến sở quản lý xe, ngày nay sau khi nộp thông tin trực tuyến là có thể tới điểm gần nhất nhận bằng.",
    "他在演讲中幽默的插话并非一时兴起，而是刻意为之，以赢得观众的好感。": "Những câu đùa hóm hỉnh xen ngang trong bài diễn thuyết của ông không phải là ngẫu hứng nhất thời, mà là sự tính toán cố ý có chủ đích nhằm chiếm trọn cảm tình của cử tọa.",
    "研究者在选择研究课题时，不能刻意去赶时髦，盲目跟风，而应结合自己的知识结构和研究兴趣。": "Người làm nghiên cứu khi lựa chọn đề tài không được cố tình chạy theo trào lưu đua đòi mù quáng, mà cần căn cứ vào nền tảng tri thức và niềm đam mê nghiên cứu của bản thân.",
    "你别这么拼命地工作，要注意身体啊！": "Bạn đừng có làm việc bạt mạng thâu đêm suốt sáng như thế, phải chú ý giữ gìn sức khỏe chứ!",
    "现场所有的粉丝们都在拼命鼓掌、尖叫，气氛热烈极了！": "Toàn thể người hâm mộ có mặt tại hiện trường đều ra sức vỗ tay reo hò, bầu không khí náo nhiệt đến tột cùng!",
    "当电梯关门时，不可强行挤入，以免发生危险。": "Khi thang máy đang khép cửa, tuyệt đối không được cố tình chen lấn lách vào để tránh xảy ra tai nạn nguy hiểm.",
    "不要直接使用电源开关键强行关机，这样易造成系统文件损坏或丢失。": "Không nên tắt nóng máy tính bằng nút nguồn cưỡng chế, làm như vậy rất dễ gây hỏng hóc hoặc mất mát các tệp tin hệ thống.",
    "理发师的手艺高超，顾客可从色板上任意挑选造型，也可带图或口头描述，只有你想不到，没有她做不到。": "Tay nghề của người thợ cắt tóc vô cùng điêu luyện, khách hàng có thể tùy ý chọn kiểu trên bảng mẫu hoặc mang ảnh tới mô tả, chỉ sợ bạn không nghĩ ra chứ không có gì cô ấy không làm được.",
    "历史就是历史，谁都不能任意修改。": "Lịch sử chính là lịch sử, không một ai có quyền tùy tiện bóp méo sửa đổi.",
    "两宋时期，海外贸易得到了空前发展，海商队伍不断壮大，侨居外商也日趋增多。": "Dưới thời Lưỡng Tống, thương mại vượt biển đã đạt được bước phát triển chưa từng có, đội ngũ thương nhân đường biển không ngừng lớn mạnh, lượng ngoại thương kiều cư cũng ngày một gia tăng.",
    "智能手机市场现已日趋饱和，如何稳中求变，成了各大厂商首要解决的问题。": "Thị trường điện thoại thông minh hiện nay đã dần tiến tới ngưỡng bão hòa, làm thế nào để giữ vững thế đứng và đột phá đổi mới đã trở thành bài toán sinh tử hàng đầu của các hãng công nghệ.",
    "虽然时间紧迫，工作量浩繁，工人们终于克服种种困难，如期完成了任务。": "Tuy thời gian gấp gáp, khối lượng công việc khổng lồ, nhưng những người công nhân rốt cuộc đã đạp bằng mọi gian khó, hoàn thành nhiệm vụ đúng kỳ hạn.",
    "为确保活动如期举行，主办方积极协调各方资源，及时解决潜在问题。": "Để bảo đảm sự kiện diễn ra đúng kế hoạch đã định, ban tổ chức đã tích cực điều phối mọi nguồn lực và kịp thời tháo gỡ các khúc mắc phát sinh.",
    "为避免员工擅自离职给公司带来麻烦和损失，用人单位可在劳动合同中提前注明相关条款。": "Để ngăn ngừa việc nhân viên tự ý bỏ việc gây xáo trộn và thiệt hại cho doanh nghiệp, đơn vị sử dụng lao động có thể ghi rõ các điều khoản ràng buộc trong hợp đồng.",
    "未经商标注册人许可，任何组织和个人均不得擅自将该商标用于同类商品上。": "Nếu chưa có sự chấp thuận của chủ sở hữu nhãn hiệu, bất kỳ tổ chức hay cá nhân nào cũng không được tự tiện sử dụng nhãn hiệu đó cho các mặt hàng cùng loại.",
    "行程中请务必听从导游安排，如私自离团，产生的一切后果均须自行承担。": "Trong suốt chuyến đi xin vui lòng tuyệt đối tuân thủ hướng dẫn của hướng dẫn viên, nếu tự ý tách đoàn, mọi hậu quả phát sinh đương sự phải tự chịu trách nhiệm.",
    "文物购销统一由文物部门负责，国内外人士不得私自进行买卖。": "Việc mua bán cổ vật được thống nhất giao cho cơ quan bảo tồn di sản quản lý, các cá nhân trong và ngoài nước tuyệt đối không được tự ý giao dịch ngầm.",
    "贵公司为我们提供了极大的帮助，特此表示感谢。": "Quý công ty đã dành cho chúng tôi sự hỗ trợ vô cùng to lớn, nay xin gửi lời cảm ơn trân trọng sâu sắc nhất.",
    "与会人员往返旅费自理，会议期间食宿由主办方承担。特此通知。": "Đại biểu tham dự tự chi trả chi phí đi lại, ăn ở trong thời gian hội nghị do ban tổ chức đài thọ. Trân trọng thông báo.",
    "不明白的不要瞎做，不该说的不要瞎说。": "Điều gì chưa hiểu rõ thì đừng làm bừa làm ẩu, điều gì không nên nói thì chớ có nói nhăng nói cuội.",
    "努力先要找准方向，否则累得半死却只是原地打转，瞎忙一通。": "Nỗ lực trước hết phải định đúng phương hướng, bằng không mệt đứt hơi mà chỉ giậm chân tại chỗ, bận rộn vô ích chẳng ra trò trống gì.",
    "为了给山区的孩子们更多的帮助，志愿者回信时还一并寄去了衣服和图书。": "Để giúp đỡ các em nhỏ vùng cao nhiều hơn, các tình nguyện viên khi gửi thư phản hồi đã tiện thể gửi kèm theo cả quần áo và sách truyện.",
    "关心支持我的朋友太多，无法一一列举，在此一并致谢。": "Những người bạn luôn quan tâm ủng hộ tôi quá nhiều không thể kể xiết từng người, xin được mượn nơi này gửi lời tri ân chân thành tới tất cả mọi người.",
    "新技术的引入，一举解决了公司长期以来成本过高、产能不足等多项难题。": "Việc ứng dụng công nghệ mới đã một phát giải quyết dứt điểm hàng loạt vấn đề nan giải bấy lâu của công ty như chi phí quá đắt đỏ và công suất trì trệ.",
    "在奥运会乒乓球男子团体决赛中，三名中国选手团结一致，一举夺冠。": "Trong trận chung kết đồng đội nam bóng bàn Olympic, ba tay vợt Trung Quốc đã đồng lòng đoàn kết, xuất sắc giành trọn ngôi vô địch.",
    "有些家庭条件好的孩子之所以会养成一些不良习惯，完全是父母一手造成的。": "Một số đứa trẻ nhà có điều kiện sở dĩ hình thành những thói hư tật xấu hoàn toàn là do chính tay cha mẹ chúng nuông chiều mà nên.",
    "为了照顾生病的妻子和年幼的孩子，他关了自己一手创办的工作室，专心守着家人。": "Để chăm sóc người vợ ốm đau và đứa con thơ dại, anh ấy đã đóng cửa studio do chính tay mình gầy dựng bấy lâu để toàn tâm toàn ý ở bên gia đình.",
    "山区孩子对知识的渴求深深打动了他，他毅然决定扎根于此，帮助孩子们圆梦大学。": "Khát khao tri thức cháy bỏng của những đứa trẻ vùng cao đã lay động sâu sắc trái tim anh, anh kiên quyết dấn thân cắm rễ tại nơi đây để chắp cánh ước mơ giảng đường cho các em.",
    "他取得博士学位后，毅然放弃了国外良好的工作条件和优厚的物质待遇，回到了祖国的怀抱。": "Sau khi lấy bằng tiến sĩ, anh ấy đã kiên quyết từ bỏ môi trường làm việc lý tưởng và mức đãi ngộ hậu hĩnh ở nước ngoài để trở về cống hiến cho quê hương đất mẹ.",
    "说到精彩之处，他有意不往下讲，吊足了大家的胃口。": "Đang nói tới đoạn cao trào hấp dẫn nhất, ông ấy cố ý ngừng bặt không kể tiếp, khiến mọi người tò mò háo hức đến nghẹt thở.",
    "我但凡提出一点儿想法，他就急于反驳，似乎有意跟我过不去。": "Phàm hễ tôi đưa ra chút ý kiến nào là anh ta liền vội vã phản bác, cứ như thể cố tình gây sự làm khó tôi vậy.",
    "尽管一周以来连续阴雨，但施工仍照常进行。": "Mặc cho suốt cả tuần mưa dầm dề rả rích, công trường thi công vẫn được tiến hành đều đặn như thường lệ.",
    "虽然她已小有名气，但仍照常在剧场认真演出，打磨演技。": "Tuy cô ấy đã có chút tên tuổi, nhưng vẫn như thường lệ nghiêm túc đứng trên sân khấu kịch để mài giũa diễn xuất.",
    "这周末店里的生意比较忙，老郭没有照例休假，而是到店帮忙接待顾客。": "Cuối tuần này quán xá khá đông khách, bác Quách không nghỉ phép như lệ thường mà tới quán phụ giúp đón tiếp khách hàng.",
    "新品宣发照例应由市场营销部负责，然而因时间紧迫，其他部门也参与了策划。": "Việc quảng bá ra mắt sản phẩm mới theo lệ thường phải do phòng Marketing chủ trì, song do thời gian quá gấp rút nên các phòng ban khác cũng cùng xắn tay vào lên kế hoạch.",
    "他年近80照样身板硬朗，精力和体力不输年轻人。": "Cụ ấy dù đã cận kề tuổi bát tuần mà vóc dáng vẫn dẻo dai vạm vỡ, tinh lực và thể lực chẳng hề thua kém bất kỳ thanh niên trai tráng nào.",
    "叶老师并未计较我之前的顶撞，照样对我倾囊相授。": "Thầy Diệp chẳng hề để bụng lời lẽ chống đối trước đây của tôi, vẫn y như trước dốc hết vốn liếng sở học truyền dạy tận tình cho tôi.",
    "我和他多年未见，本想留他多住几天，可他执意不肯，说是家中有事。": "Tôi và anh ấy bao năm không gặp, vốn muốn giữ anh ở lại chơi thêm vài hôm, nhưng anh cứ khăng khăng không chịu, bảo là trong nhà có việc gấp.",
    "她不顾家人、朋友的劝说，病还没好就执意回到工作岗位。": "Mặc cho người thân bạn bè hết lời khuyên can, cơn bệnh chưa dứt hẳn mà cô ấy đã nhất quyết quay lại vị trí công tác.",
    "一夜狂风暴雨过后，气温骤然下降了十几度。": "Sau một đêm mưa bão gầm rú cuồng phong, nhiệt độ bỗng chốc tụt dốc không phanh hơn mười độ C.",
    "鱼相继在水中跃起，原本平静的湖面，骤然起了波澜。": "Từng đàn cá nối đuôi nhau quẫy mình tung tăng dưới nước, mặt hồ vốn đang phẳng lặng như gương bỗng chốc dậy sóng lăn tăn.",
    "大幕拉开，节目主持人走上舞台，他首先感谢了观众的到来，然后逐一介绍在场嘉宾。": "Màn nhung hé mở, người dẫn chương trình bước ra sân khấu, trước tiên gửi lời cảm ơn khán giả đã tới dự, sau đó lần lượt giới thiệu từng vị khách quý có mặt.",
    "考生入场后对号入座，将准考证和有效身份证件放在桌子右上角，以备监考员逐一核查。": "Thí sinh sau khi vào phòng thi ngồi đúng số báo danh, đặt thẻ dự thi và giấy tờ tùy thân hợp lệ lên góc phải bàn để giám thị lần lượt đối chiếu kiểm tra.",
    "为了吃到最鲜美的河豚，远在新疆的刘先生跨越三千多公里专程来到扬中。": "Để được thưởng thức món cá nóc tươi ngon nhất, ông Lưu ở tận Tân Cương xa xôi đã vượt hơn 3.000 cây số cất công lặn lội đến Dương Trung.",
    "有一年，我专程去南京拜访了恩师，导师已年逾古稀，但依然精神矍铄。": "Có một năm nọ, tôi đã lặn lội vào tận Nam Kinh thăm lại người thầy đáng kính, người nay đã ngoài thất tuần nhưng tinh thần vẫn quắc thước minh mẫn lạ thường.",
    # 016
    "文学上的分类只反映文学作品的特点而非价值的高低，通俗小说不见得不高雅，不见得不严肃，而那些所谓的非通俗小说，也并非都是精品。": "Sự phân loại trong văn học chỉ phản ánh đặc trưng của tác phẩm chứ không quyết định đẳng cấp giá trị cao thấp: tiểu thuyết đại chúng chưa chắc đã không thanh nhã, chưa chắc đã thiếu đứng đắn; còn những tác phẩm được dán mác tinh hoa thì cũng đâu phải cuốn nào cũng là kiệt tác.",
    "这件事非常麻烦，你就是让比我厉害十倍的人去办，也不见得能办成。": "Việc này vô cùng rắc rối, bạn có cậy nhờ người giỏi gấp mười lần tôi đi xử lý thì cũng chưa chắc đã làm nên chuyện đâu.",
    "年轻人绝不应为了攀比和享乐而过度消费，甚至背上难以偿还的债务。": "Giới trẻ tuyệt đối không nên vì tâm lý đua đòi và hưởng thụ nhất thời mà tiêu xài hoang phí, để rồi gánh trên vai những khoản nợ nần không thể gượng dậy nổi.",
    "他那么聪明的人，绝不会干这种傻事。": "Một người thông minh sáng dạ như anh ấy tuyệt đối sẽ chẳng bao giờ làm cái trò ngốc nghếch dại dột đó đâu.",
    "即将告别学生时代，我心有千言反而无从说起。": "Giây phút sắp sửa chia tay giảng đường thời cắp sách, lòng tôi trào dâng muôn vàn tâm sự mà lại chẳng biết mở lời bắt đầu từ đâu.",
    "此次会议内容严格保密，外界对其无从得知。": "Nội dung cuộc họp lần này được bảo mật tuyệt đối, dư luận bên ngoài hoàn toàn không có cách nào nắm bắt thông tin.",
    "她满墙贴的都是舞台上演奏的照片，音乐对她的重要性无须多言。": "Bức tường phòng cô ấy dán kín những bức ảnh biểu diễn trên sân khấu, tầm quan trọng của âm nhạc đối với đời cô thiết nghĩ không cần phải nói thêm lời nào nữa.",
    "“往者不可谏，来者犹可追”，无须为过去的失误而懊悔，重要的是把握现在，展望未来。": "'Chuyện đã qua không thể vãn hồi, việc tương lai vẫn còn có thể đuổi kịp', không việc gì phải gặm nhấm ân hận vì những sai lầm trong quá khứ, điều cốt yếu là nắm chắc hiện tại và vững tin hướng tới tương lai.",
    "她的演唱技巧卓越且感情真挚，让台下评委们无可指摘。": "Kỹ thuật thanh nhạc xuất chúng cùng cảm xúc dạt dào chân thành của cô khiến toàn bộ ban giám khảo bên dưới hoàn toàn không thể chê trách hay bắt bẻ vào đâu được.",
    "当被问及该片是否以悲剧结尾，女主表示已签署保密协议，对此无可奉告。": "Khi được gặng hỏi liệu bộ phim có khép lại bằng một kết thúc bi kịch hay không, nữ diễn viên chính cho hay mình đã ký cam kết bảo mật nên về việc này xin miễn bình luận.",
    "女儿春节在外未能回家，询问父母近况，二老回复说：“一切平安，勿念。”": "Con gái dịp tết bận việc phương xa không thể về sum họp, nhắn tin hỏi thăm tình hình bố mẹ, hai cụ nhắn lại ngắn gọn: 'Mọi sự đều bình yên, con chớ bận lòng'.",
    "室内若发生煤气泄漏，应立即打开门窗通风，切勿使用明火。": "Trong phòng nếu phát hiện rò rỉ khí gas, cần lập tức mở toang các cửa sổ cho thông thoáng, tuyệt đối chớ có sử dụng lửa ngọn.",
    # 017
    "快乐的人，必定是对生活有深刻洞察力的人，必定是内心富于诗意的人。": "Một con người luôn vui tươi nhất định phải là người có cái nhìn thấu suốt sâu sắc về cuộc đời, và ắt hẳn phải mang trong mình một tâm hồn giàu chất thơ.",
    "以你的资质，假以时日必定会“青出于蓝而胜于蓝”。": "Với tố chất thông minh của bạn, chỉ cần cho thêm thời gian thì nhất định sẽ 'trò giỏi hơn thầy, hậu sinh khả úy'.",
    "诚信经营方能行稳致远，投机取巧必将自取灭亡。": "Kinh doanh giữ trọn chữ tín mới có thể đứng vững đi xa, còn mưu mô trục lợi tắt lối ắt sẽ tự chuốc lấy diệt vong.",
    "这次友好访问，必将使两国关系上升到一个新的阶段。": "Chuyến thăm hữu nghị lần này tất yếu sẽ đưa quan hệ bang giao giữa hai quốc gia bước lên một tầm cao mới.",
    "投资者须细细分析股票走势。若一时无把握，出手不妨“慢一拍”。": "Nhà đầu tư cần phải phân tích tỉ mỉ chiều hướng dao động của cổ phiếu. Nếu nhất thời chưa nắm chắc phần thắng, khi xuống tiền chi bằng cứ 'chậm lại một nhịp' xem sao.",
    "巧用果蔬饰家居，可拥有回味无穷的诗情画意，有兴趣的不妨一试。": "Khéo léo tận dụng hoa quả củ quả để bài trí tổ ấm có thể mang lại chất thơ ý họa dư vị vô cùng, ai có hứng thú thiết nghĩ cũng nên thử một phen.",
    "眼看着周围的同事朋友升职发财，佳佳不免跟丈夫多唠叨了几句。": "Nhìn bạn bè đồng nghiệp xung quanh thăng quan tiến chức phát tài, Giai Giai khó tránh khỏi việc cằn nhằn đôi câu với chồng.",
    "每逢下雨天，她就不免想起一桩伤心的往事。": "Mỗi độ trời đổ mưa rào, lòng cô lại không khỏi bùi ngùi nhớ về một chuyện buồn ngày cũ.",
    "我让他走慢点儿，等等我，他反倒加快了脚步。": "Tôi bảo anh ấy bước chậm lại một chút để chờ tôi với, anh ta ngược lại còn rảo bước nhanh hơn.",
    "他出身于一个医学世家，却对行医丝毫不感兴趣，反倒对绘画情有独钟。": "Anh ấy xuất thân từ một dòng dõi danh y thế gia, vậy mà chẳng mảy may hứng thú với nghề bốc thuốc, trái lại chỉ say mê đắm đuối với hội họa.",
    "这事儿没必要非得今天就定，你再回去好好考虑一下。": "Chuyện này không cần thiết cứ nhất quyết phải chốt ngay trong ngày hôm nay đâu, bạn cứ về nhà suy nghĩ lại cho thật chín chắn.",
    "要想练就一手好的毛笔字，非得花十年甚至数十年功夫不可。": "Muốn rèn nên những nét chữ thư pháp tuyệt bút, nhất định phải khổ luyện mười năm thậm chí hàng mấy chục năm ròng mới thành.",
    "我分明看见他从办公室拿走了一份文件，可他就是不承认。": "Tôi rõ rành rành tận mắt thấy anh ta lấy đi một tập tài liệu từ văn phòng, vậy mà anh ta sống chết không chịu nhận.",
    "平坦宽阔的水泥路，稳重气派的小洋房，四周群山环绕，溪水潺潺。这哪里还是一个贫穷落后的小村庄，分明是一个世外桃源！": "Con đường bê tông thênh thang phẳng phiu, những căn biệt thự mini bề thế khang trang, bốn bề núi non ôm ấp suối chảy róc rách. Đây đâu còn là một ngôi làng nghèo nàn lạc hậu nữa, rõ ràng là chốn bồng lai tiên cảnh trần gian!",
    "他真是个精明能干的小伙子，怪不得厂长这么器重他。": "Cậu ấy đúng là một chàng trai tháo vát cơ trí, hèn chi giám đốc nhà máy lại coi trọng cậu ta đến thế.",
    "——你听说了吗？小李当上部门经理了！": "—— Cậu đã nghe tin gì chưa? Tiểu Lý được thăng chức làm trưởng phòng rồi đấy!",
    "——怪不得！我说他今天怎么突然说要请客了呢。": "—— Thảo nào! Tớ bảo sao hôm nay hắn ta tự nhiên lại hào phóng đòi khao cơ chứ.",
    "他非常热情地让我尝尝这道菜，说这是这家店的招牌，我一吃，果真不错。": "Anh ấy vô cùng niềm nở mời tôi nếm thử món này, bảo đây là món tủ trứ danh của quán, tôi vừa nhấm nháp một miếng, quả nhiên ngon tuyệt cú mèo.",
    "九寨沟的风景果真名不虚传，如人间仙境一般。": "Cảnh sắc Cửu Trại Câu quả nhiên danh bất hư truyền, hệt như chốn bồng lai tiên cảnh giữa cõi phàm trần.",
    "见到她的第一眼，我就觉得她是一个有故事的人。果真，这位看似柔弱的女性承受了许多不为人知的困苦与艰辛。": "Ngay từ ánh nhìn đầu tiên, tôi đã cảm nhận cô ấy là một người chất chứa nhiều tâm sự. Quả đúng như vậy, người phụ nữ trông có vẻ mảnh mai yếu đuối này đã phải gánh gồng bao nỗi đắng cay gian truân mà chẳng ai thấu tỏ.",
    "北京的胡同多得出奇，而且样子大同小异，穿梭其中极易迷路。好在北京人热心，问路时总能得到帮助。": "Ngõ ngách hẻm phố ở Bắc Kinh nhiều đến kỳ lạ, vả lại dáng dấp na ná giống nhau, luồn lách bên trong rất dễ lạc lối. May sao người Bắc Kinh rất nhiệt tình, hễ hỏi đường là luôn được chỉ bảo tận tình.",
    "这部电影的动作设计复杂且全部实地取景，好在他凭借多年的武术功底，成功完成了拍摄任务。": "Bộ phim này các pha hành động thiết kế cực kỳ phức tạp lại quay ngoại cảnh thực tế toàn bộ, may nhờ anh ấy có căn cơ võ thuật nhiều năm nên đã hoàn thành xuất sắc cảnh quay.",
    "清者自清，你自己是清白的，何必跟误会你的人解释那么多。": "Người ngay thẳng tự khắc thanh cao trong sạch, bản thân bạn không thẹn với lòng thì hà tất phải tốn hơi phân trần với những kẻ hiểu lầm mình.",
    "你为了满足自己的虚荣心，花这么多钱打肿脸充胖子，何必呢？": "Cậu vì muốn thỏa mãn thói hư vinh hão huyền mà vung tiền quá trán để cố làm ra vẻ sang giàu, việc gì phải khổ thế cơ chứ?",
    "整场比赛的战术执行得几乎无懈可击，对手在我方的猛烈进攻和严密防守下竟一分未得。": "Chiến thuật của toàn trận đấu được triển khai hoàn hảo không một vết xước, đối thủ dưới sức ép tấn công vũ bão và phòng ngự kín kẽ của chúng ta vậy mà chẳng ghi nổi dù chỉ một điểm danh dự.",
    "张校长的家离学校只有两公里，但是她长期住在学校，最长的一次竟有半年没回过家。": "Nhà của cô hiệu trưởng Trương chỉ cách trường có 2 cây số, vậy mà cô thường xuyên cắm trại ăn ngủ tại trường, đợt lâu nhất thế mà tròn nửa năm không hề bước chân về nhà.",
    "事情明明就是他做的，可他愣不承认。": "Chuyện rõ mười mươi là do hắn ta làm, vậy mà hắn cứ trơ tráo nhất quyết không chịu nhận tội.",
    "出身贫寒的他，白手起家，愣是将一个小小的餐馆做成了全国连锁的品牌。": "Xuất thân từ bần hàn cơ cực, hai bàn tay trắng dựng nghiệp, anh ấy thế mà đã biến một quán ăn nhỏ xíu thành một chuỗi thương hiệu nhượng quyền phủ sóng toàn quốc.",
    "他这人一向无事不登三宝殿，今天忽然登门拜访，莫非有什么棘手的事相求？": "Con người anh ta vốn xưa nay không có việc thì chẳng bao giờ ghé chân, hôm nay bỗng dưng đến gõ cửa bái phỏng, chẳng lẽ lại có chuyện gai góc gì muốn nhờ vả chăng?",
    "望着孩子们拿到爱心图书时激动的神情，我心中涌起了强烈的幸福和满足，莫非这就是所谓的“赠人玫瑰，手有余香”？": "Nhìn vẻ mặt rạng rỡ xúc động của lũ trẻ khi nhận được những cuốn sách yêu thương, trong lòng tôi dâng lên niềm hạnh phúc ngập tràn, chẳng lẽ đây chính là điều mà người ta vẫn nói: 'Tặng người hoa hồng, tay lưu hương thơm'?",
    "物美价廉的菜品，清爽整洁的装修，热情周到的服务，难怪这家店的生意越来越红火。": "Món ăn ngon bổ rẻ, không gian bài trí thoáng đãng sạch sẽ, phong cách phục vụ ân cần chu đáo, hèn chi quán ăn này làm ăn ngày một phát đạt hưng thịnh.",
    "置身湟川三峡，你可以同时欣赏到险峻雄伟的悬崖绝壁和深邃秀美的青山碧水，难怪这里被誉为“岭南诗画走廊”。": "Đặt chân đến Tam Hiệp Hoàng Xuyên, bạn có thể đồng thời chiêm ngưỡng những vách đá dựng đứng hiểm trở hùng vĩ cùng non xanh nước biếc sâu thẳm hữu tình, hèn chi nơi đây được ngợi ca là 'Hành lang thơ họa Lĩnh Nam'.",
    "为了抓住这个宝贵的工作机会，他宁可每天双城通勤。": "Để nắm bắt cơ hội việc làm vô giá này, anh ấy thà chấp nhận mỗi ngày đi đi về về vất vả giữa hai thành phố.",
    "母亲望着怀中脸烧得通红的孩子，心疼不已，宁可病都生在自己身上。": "Người mẹ ôm đứa con mặt mày sốt đỏ bừng trong lòng mà đứt từng khúc ruột, thà ước sao mọi đau đớn bệnh tật cứ trút hết lên tấm thân mình.",
    "如果贵公司无法保证按时交付，我们宁愿放弃此次合作。": "Nếu như quý công ty không thể cam kết bàn giao đúng tiến độ, chúng tôi thà hủy bỏ thương vụ hợp tác lần này.",
    "每当攻克一个技术难题后，他不喜和别人一起庆功，宁愿一个人暗自回味。": "Mỗi khi chinh phục được một nút thắt kỹ thuật hóc búa, anh ấy không thích chè chén ăn mừng cùng đám đông, mà thà một mình lặng lẽ chiêm nghiệm niềm vui sâu lắng.",
    "我那时正为找房子发愁，碰巧有个同学租的两居室空出了一个房间，我就搬过去住了。": "Hồi đó tôi đang đau đầu vì chuyện tìm thuê nhà, vừa khéo có một người bạn cùng lớp thuê căn hộ hai phòng ngủ bị trống một phòng, thế là tôi dọn sang ở luôn.",
    "我刚买完东西准备回家，碰巧在商场门口遇见了多年不见的同窗，我们便去小酌了几杯，谈谈各自的经历。": "Tôi vừa sắm đồ xong chuẩn bị về nhà thì tình cờ chạm mặt người bạn học cũ bao năm không gặp ngay trước cửa trung tâm thương mại, thế là hai đứa rủ nhau đi nhâm nhi vài chén hàn huyên sự đời.",
    "台风早不来，晚不来，偏偏赶在这个时候来！航班取消了，我的旅游计划全泡汤了。": "Cơn bão sớm chẳng đổ bộ, muộn không ập tới, cứ oái oăm đè đúng lúc này mà quét qua! Chuyến bay bị hủy, toàn bộ kế hoạch du lịch của tôi coi như tan thành mây khói.",
    "欣赏风景一般是用眼睛看，但东湖的设计者却偏偏要你用耳朵听景、用鼻子闻景。": "Thưởng ngoạn cảnh sắc thông thường là dùng mắt ngắm, nhưng người thiết kế Đông Hồ lại cứ nhất quyết muốn bạn dùng đôi tai để lắng nghe và dùng khứu giác để hít hà phong cảnh.",
    "吃饭时有可口的餐食，睡觉时有香软的床榻，逛街时恰巧听到钟爱的乐曲，这些瞬间都足以让我感受到生活的美好。": "Khi dùng bữa có đồ ăn hợp khẩu vị, lúc đi ngủ có chăn êm nệm ấm, khi dạo phố tình cờ nghe được khúc nhạc mình yêu thích, những khoảnh khắc ấy đã đủ khiến tôi cảm nhận được sự ngọt ngào của cuộc sống.",
    "因为“鱼”恰巧跟“余”字同音，所以年夜饭饭桌上一定有鱼，是希望“年年有余”的意思。": "Vì chữ 'ngư' (cá) vừa khéo đồng âm với chữ 'dư' (dư dả), cho nên trên mâm cơm tất niên dứt khoát phải có món cá, ngụ ý cầu chúc 'năm năm có dư'.",
    "雪山海拔较高，游览过程中易产生高原反应，切记根据自身情况量力而行。": "Núi tuyết có độ cao lớn so với mặt nước biển, trong quá trình tham quan rất dễ bị sốc độ cao, nhất thiết phải lượng sức mình tùy theo thể trạng cá nhân.",
    "家中常用药应少而精，切不可盲目囤积大量药品，避免过期造成浪费。": "Tủ thuốc gia đình chỉ nên trữ gọn và tinh, tuyệt đối chớ có tích trữ bừa bãi số lượng lớn thuốc men để tránh hết hạn gây lãng phí tốn kém.",
    "这家火锅店口碑极好，很多顾客情愿排队等一两个小时，也要在这里吃。": "Quán lẩu này danh tiếng lẫy lừng, rất nhiều thực khách thà chịu khó xếp hàng ròng rã suốt một hai tiếng đồng hồ cũng quyết ăn cho bằng được.",
    "很多商家其实并不情愿动辄促销，但看到竞品价格一再跳水，自己也只能被迫参与价格战。": "Nhiều chủ tiệm thực lòng chẳng hề muốn hơi một tí là tung khuyến mãi giảm giá, nhưng nhìn giá đối thủ liên tục lao dốc, bản thân đành cắn răng bị cuốn vào cuộc chiến phá giá.",
    "如果这则新闻的真实性得到确认，势必引起全社会的强烈反响。": "Nếu như tính xác thực của bản tin này được kiểm chứng, tất yếu sẽ dấy lên làn sóng phản ứng dữ dội trong toàn xã hội.",
    "如果这个关键技术问题得不到解决，公司的竞争力势必会受到影响。": "Nếu như nút thắt kỹ thuật then chốt này không được tháo gỡ dứt điểm, sức cạnh tranh của công ty tất yếu sẽ bị giáng một đòn nặng nề.",
    "前往景区的路上已堵得水泄不通，我们索性直接下车步行。": "Đường tiến vào khu danh thắng đã tắc nghẽn kẹt cứng như nêm, chúng tôi dứt khoát nhảy luôn xuống xe đi bộ cho nhanh.",
    "他考了几次都没通过，索性不考了。": "Cậu ấy thi mấy lần liền đều trượt vỏ chuối, đâm ra nản lòng dứt khoát chẳng thèm thi thố gì nữa.",
    "我们为了这次竞赛准备了很长时间，可万万没有想到，组委会突然宣布比赛取消，而且没给出合理解释。": "Chúng tôi đã dồn bao tâm sức chuẩn bị cho hội thi lần này suốt một thời gian dài, thế nhưng muôn vạn lần không ngờ tới là ban tổ chức lại đùng một cái thông báo hủy giải mà chẳng buồn đưa ra lời giải thích thỏa đáng.",
    "事实表明，代言人与品牌的匹配程度对商品销售有着重要影响，企业万万不可轻视。": "Thực tiễn đã chứng minh rằng mức độ tương thích giữa đại sứ hình ảnh và thương hiệu có tác động sống còn tới doanh số sản phẩm, doanh nghiệp muôn vàn chớ nên xem nhẹ.",
    "文章本身不好，安上一个好题目也无济于事；但文章好而题目不好，就未免令人惋惜了。": "Bản thân bài viết đã dở tệ thì có đặt một cái tít kêu như chuông cũng chẳng ích gì; thế nhưng bài viết xuất sắc mà tiêu đề lại nhạt nhòa thì e rằng thật đáng tiếc nuối biết bao.",
    "没有取得理想结果，他未免有些沮丧，此时最需要的是鼓励和安慰。": "Không đạt được kết quả như kỳ vọng, anh ấy khó tránh khỏi cảm giác chán nản muộn phiền, lúc này điều cần thiết nhất là những lời động viên và an ủi vỗ về.",
    "演出期间，请各位观众务必将手机调至静音，以免影响他人。": "Trong suốt buổi biểu diễn, kính đề nghị quý khán giả nhất định phải chuyển điện thoại sang chế độ rung hoặc im lặng để tránh làm phiền tới người xung quanh.",
    "因活动现场座位有限，请务必提前报名，额满即止。": "Do số lượng chỗ ngồi tại hội trường có hạn, kính mong quý vị nhất thiết phải đăng ký trước, đủ số lượng ban tổ chức sẽ khóa sổ.",
    "他急忙把生病的孩子送去医院治疗，医生检查后说：“这孩子幸好送得及时，迟一点就没救了。”": "Anh ấy hối hả đưa đứa trẻ ốm nặng tới bệnh viện cấp cứu, bác sĩ khám xong liền bảo: 'Đứa nhỏ này may mà đưa tới kịp thời, chỉ chậm chút nữa thôi là vô phương cứu chữa'.",
    "我听见他的话后，吃惊地朝四周看了看，幸好附近无人，这才放了心。": "Nghe lời anh ấy nói, tôi giật mình đưa mắt đảo quanh bốn phía, may nhờ xung quanh không có bóng người, lúc ấy mới thở phào trút bỏ nỗi lo.",
    "今天的活动我幸亏没去凑热闹，去了也是人挤人，什么也看不见。": "Sự kiện hôm nay may phước là tôi không đi chen lấn hóng hớt, có đi thì cũng người nêm như cối xay, chẳng xem được trò trống gì.",
    "刘女士不小心把手提包落在了出租车上，幸亏遇到林师傅这样拾金不昧的司机，主动把包交还给了她。": "Chị Lưu sơ ý bỏ quên túi xách trên xe taxi, may phước gặp được người tài xế thật thà tốt bụng như bác Lâm, đã chủ động liên hệ trao trả lại nguyên vẹn chiếc túi cho chị.",
    "乌云遮不住太阳，正义终究会战胜邪恶。": "Mây đen không thể che nổi ánh mặt trời chói lọi, chính nghĩa rốt cuộc trước sau vẫn sẽ chiến thắng tà ác.",
    "漂泊的游子，无论在外如何坚强，回到家也终究是个孩子。": "Những đứa con tha hương cầu thực, dẫu bươn chải ngoài đời kiên cường bản lĩnh đến đâu, khi trở về bên mái ấm gia đình rốt cuộc vẫn chỉ là một đứa trẻ thơ.",
    "我要去海南旅游了，你最近不也休假吗，何不一起去？": "Tớ chuẩn bị đi du lịch đảo Hải Nam đây, dạo này cậu cũng đang nghỉ phép đó thôi, sao chúng mình không cùng đi cho vui?",
    "在这样一个大城市的小区，雨后还能听到蛙声，真的令人欣喜。我们何不把新居叫做“听蛙楼”？": "Giữa khu chung cư của một đại đô thị phồn hoa như thế này mà sau cơn mưa vẫn lắng nghe được tiếng ếch kêu râm ran, thật khiến lòng người ngập tràn thi vị. Sao chúng ta không đặt tên cho tổ ấm mới này là 'Thính Oa Lâu'?",
    "她一向被众星捧月，何尝受过这样的冷遇，心中气愤不已。": "Cô ấy từ xưa tới nay luôn được người đời tung hô chiều chuộng như sao vây quanh trăng, nào đã từng nếm qua sự ghẻ lạnh hờ hững như thế này bao giờ, đâm ra trong lòng tức tối không thôi.",
    "在逆境下不气馁、不后悔，这才是强者该有的逻辑。体育比赛是这样，其他事情何尝不也是如此呢？": "Trước nghịch cảnh không nản lòng thoái chí, không ân hận thở than, đó mới chính là bản lĩnh đích thực của bậc cường giả. Thi đấu thể thao là như thế, và vạn sự trên đời nào có khác gì đâu?",
    "你60岁的人了，每个月好几千的退休金，何苦再出来打零工？": "Bác đã ngoài 60 tuổi rồi, mỗi tháng đều đặn nhận mấy nghìn tệ lương hưu, hà tất việc gì phải cực thân ra ngoài làm thêm làm mướn nữa làm chi?",
    "小张刚毕业，社会经验不足，犯点错误也难免，你何苦为难她呢？": "Tiểu Trương mới ra trường va vấp xã hội chưa nhiều, phạm chút lỗi lầm cũng là điều khó tránh, cậu việc gì phải làm khó con bé đến mức ấy chứ?",
    # 018
    "该片剧情严谨，全员演技在线，真乃一部不可多得的佳作。": "Cốt truyện của bộ phim này vô cùng chặt chẽ, toàn bộ dàn diễn viên đều diễn xuất đỉnh cao, quả thực xứng danh là một tuyệt phẩm hiếm có khó tìm.",
    "我问他是怎么知道的，他神秘地说：“此乃天机，不可泄露。”": "Tôi gặng hỏi làm sao anh ta biết được tin ấy, anh ta làm vẻ huyền bí cười bảo: 'Đây chính là thiên cơ, không thể tiết lộ'.",
    # 019
    "打这天起，小赵替父亲担起了全家的重担。": "Kể từ ngày hôm ấy trở đi, Tiểu Triệu đã thay cha gánh vác toàn bộ gánh nặng mưu sinh của cả gia đình.",
    "他悄声说这可是件宝贝，打皇宫里流出来的。": "Hắn ta hạ giọng thì thầm bảo đây đích thị là món bảo vật gia truyền, tuồn từ tận trong hoàng cung ra ngoài đấy.",
    # 020
    "当着这么多人，那人只好把话咽了下去。": "Trước mặt bao nhiêu con người đang chăm chú nhìn vào, người nọ đành nuốt ngược lời định nói vào trong họng.",
    "大家聊得正高兴，她却当着大家的面掉下泪来。": "Mọi người đang trò chuyện vui vẻ rôm rả, thế mà cô ấy lại rơi nước mắt ngay trước mặt bàn dân thiên hạ.",
    "论坛期间，各国专家就共同感兴趣的专题进行了探讨和交流。": "Trong thời gian diễn ra diễn đàn, các chuyên gia từ nhiều nước đã tiến hành trao đổi và thảo luận sâu rộng về những chuyên đề cùng quan tâm.",
    "就离婚后的财产分割问题，双方产生了激烈的争论。": "Xung quanh vấn đề phân chia tài sản sau khi ly hôn, đôi bên đã nảy sinh cuộc tranh cãi vô cùng gay gắt.",
    # 021
    "我们本着“友谊第一，比赛第二”的精神，充分享受比赛的乐趣。": "Chúng tôi trên tinh thần 'hữu nghị là trên hết, thi đấu là thứ hai' đã tận hưởng trọn vẹn niềm vui của cuộc tranh tài.",
    "虽然我和小孙素日关系更近，但本着实事求是的态度，我还是把票投给了小魏。": "Tuy thường ngày tôi và Tiểu Tôn có mối quan hệ thân thiết hơn, nhưng trên tinh thần khách quan tôn trọng thực tế, tôi vẫn bỏ lá phiếu bầu cho Tiểu Ngụy.",
    "基于调研的结果，我们精准定位了产品的目标市场。": "Dựa trên các kết quả khảo sát thực địa, chúng tôi đã định vị chuẩn xác phân khúc thị trường mục tiêu cho sản phẩm.",
    "这部电影是基于真实事件改编而成的。": "Bộ phim điện ảnh này được phóng tác và cải biên dựa trên những sự kiện có thật trong đời thực.",
    "鉴于你在此次项目中的突出表现，公司决定对你予以嘉奖。": "Xét thấy những cống hiến và màn thể hiện xuất sắc của bạn trong dự án lần này, ban giám đốc công ty quyết định trao tặng bằng khen và phần thưởng cho bạn.",
    "鉴于市场需求和用户偏好的不断变化，产品设计应适时转变策略，适应市场发展。": "Xét đến nhu cầu thị trường và thị hiếu người dùng không ngừng biến đổi, việc thiết kế sản phẩm cần kịp thời chuyển dịch chiến lược để thích ứng với xu thế.",
    "决议成文程序严格，须经全体会议或代表大会讨论通过才能生效。": "Quy trình ban hành nghị quyết được thực hiện hết sức nghiêm ngặt, bắt buộc phải qua phiên họp toàn thể hoặc đại hội đại biểu thảo luận thông qua thì mới có hiệu lực thi hành.",
    "经医生细心诊治，哥哥身体状况日渐好转，已经可以自行下床行走了。": "Qua bàn tay chẩn trị tận tình của các bác sĩ, tình trạng sức khỏe của anh trai ngày một khởi sắc, nay đã có thể tự mình xuống giường tản bộ.",
    "经研究，公司决定把这一重要的新款产品交由你全权负责。": "Sau khi nghiên cứu kỹ lưỡng, ban lãnh đạo công ty quyết định giao toàn quyền phụ trách dòng sản phẩm mới quan trọng này cho bạn.",
    "一些无良的鉴定专家不依市场价值而是依主观价值评定东西等级的行为，严重扰乱了市场秩序。": "Hành vi của một số chuyên gia giám định vô lương tâm không dựa theo giá trị thị trường mà lại dựa vào cảm tính chủ quan để định cấp bậc món đồ đã làm lũng đoạn nghiêm trọng trật tự thị trường.",
    "依我看，你在这件事的处理上有失公允。": "Theo như tôi thấy, trong cách xử lý việc này bạn đã có phần thiếu công tâm thỏa đáng.",
    # 022
    "鉴于近期设备故障频发，技术部门决定对相关设备进行全面维护。": "Xét thấy thời gian gần đây máy móc liên tục xảy ra sự cố hỏng hóc, phòng kỹ thuật đã quyết định tiến hành bảo dưỡng toàn diện các trang thiết bị liên quan.",
    "鉴于被告人严某主动上缴违法所得，认罪态度良好，可酌情从轻处罚。": "Xét thấy bị cáo Nghiêm mỗ đã chủ động nộp lại toàn bộ số tiền phi pháp thu lợi bất chính, thái độ nhận tội thành khẩn, nên có thể châm chước giảm nhẹ hình phạt.",
    "你们的方案非常详细，况且已经得到了业内专家的肯定，相信实施起来不会有什么问题。": "Phương án của các bạn vô cùng chi tiết, vả lại đã nhận được sự thẩm định đồng thuận của các chuyên gia đầu ngành, tin rằng khi triển khai thực tế sẽ không gặp trở ngại gì.",
    "要告别近二十年的舞台生涯，她真的十分不舍，况且，隔行如隔山，不跳舞她又能改行做些什么呢？": "Phải giã từ sự nghiệp múa trên sân khấu gần 20 năm gắn bó, lòng cô thực sự muôn phần luyến tiếc, vả lại cách ngành như cách núi, nếu không múa nữa thì cô biết đổi nghề làm gì đây?",
    "有缘无缘不可强求，免得徒增烦恼。": "Duyên đến duyên đi là lẽ tự nhiên không thể cưỡng cầu, buông bỏ cho thanh thản để tránh chuốc thêm muộn phiền sầu não.",
    "去往一个陌生的国家或地区，须了解当地的治安环境、文化禁忌，免得招来麻烦。": "Đặt chân đến một quốc gia hay vùng miền xa lạ, cần phải tìm hiểu kỹ tình hình an ninh và các điều kiêng kỵ văn hóa bản địa, kẻo lại rước họa vào thân.",
    "事情要是能顺利解决最好，若不行，就得另寻其他门路了。": "Sự việc nếu giải quyết êm xuôi được là tốt nhất, bằng như không xong, ta buộc phải tính kế tìm cửa khác.",
    "若是购买的产品有任何质量问题，消费者可在七天之内无理由退换。": "Nếu như sản phẩm mua về có bất kỳ lỗi chất lượng nào, người tiêu dùng hoàn toàn có quyền đổi trả vô điều kiện trong vòng 7 ngày.",
    "倘若一开始她就懂得精打细算，日子也不会过得这么捉襟见肘了。": "Nếu như ngay từ đầu cô ấy biết chi tiêu vén khéo căn cơ, cuộc sống gia đình đâu đến nỗi rơi vào cảnh giật gấu vá vai túng quẫn thế này.",
    "我现在已经不想再听你说什么豪言壮语了。倘若五年后你能混出点名堂，就当我今日有眼不识泰山。": "Giờ đây tôi chẳng còn hứng thú nghe những lời đao to búa lớn của anh nữa. Nếu như 5 năm sau anh có thể làm nên công trạng rạng danh, thì coi như hôm nay mắt tôi có tròng mà như mù không thấy thái sơn.",
    "切莫轻易向陌生人转账汇款，以防上当受骗。": "Tuyệt đối chớ có nhẹ dạ chuyển khoản tiền bạc cho người lạ, nhằm đề phòng bị sập bẫy lừa đảo.",
    "这次安全事故造成的惨烈后果，希望各位引以为戒，以防类似的悲剧再度发生。": "Hậu quả thảm khốc do vụ tai nạn lao động lần này gây ra, mong toàn thể mọi người lấy đó làm bài học răn mình để ngăn ngừa thảm kịch tương tự tái diễn.",
    # 023
    "空气湿闷，加之窗外嘈杂不已，使得她彻夜未眠。": "Không khí oi bức ngột ngạt, cộng thêm tiếng ồn ào inh ỏi ngoài cửa sổ, khiến cô ấy trằn trọc suốt đêm không chợp mắt nổi.",
    "他出众的能力加之丰富的工作经验是他职位迅速晋升的关键所在。": "Năng lực xuất chúng cộng thêm bề dày kinh nghiệm thực chiến chính là chìa khóa vàng giúp anh thăng tiến thần tốc trong sự nghiệp.",
    "这件衣服的刺绣工艺异常复杂，单是绣一朵花就需要花费数月乃至一年的时间。": "Kỹ thuật thêu thùa trên chiếc áo này vô cùng cầu kỳ tinh xảo, chỉ riêng thêu một đóa hoa thôi đã ngốn mất vài tháng trời thậm chí cả năm ròng.",
    "我被他对文学的热爱和执着深深地打动了，乃至我回去之后还不能平静。": "Tôi bị lòng đam mê và sự kiên trì cháy bỏng của ông dành cho văn chương làm lay động sâu sắc, đến mức sau khi trở về nhà tâm trí tôi vẫn bồi hồi khôn nguôi.",
    "受欢迎且传播力强的文章，在选题策划方面一定高出一筹。": "Một bài viết vừa được công chúng đón nhận nồng nhiệt lại vừa có sức lan tỏa mạnh mẽ thì chắc chắn khâu lên ý tưởng chọn đề tài phải cao tay hơn hẳn một bậc.",
    "醉酒驾车造成他人死亡的驾驶员被当场吊销驾照，且终身不予重新申请。": "Tài xế say rượu lái xe làm chết người bị tước bằng lái ngay tại chỗ, hơn nữa còn bị cấm vĩnh viễn không bao giờ được cấp lại bằng.",
    # 024
    "他很谦虚地将自己的成功归结为运气好罢了。": "Anh ấy rất đỗi khiêm nhường khi chỉ quy kết mọi thắng lợi của mình là nhờ may mắn mà thôi.",
    "那些我们一度以为难以承受的挫折，终将会变成人生宝贵的经历，只是时间的问题罢了。": "Những trắc trở gian nan mà ta từng ngỡ rằng không thể nào gánh vác nổi, rồi đây sẽ hóa thành vốn sống vô giá của một đời người, âu cũng chỉ là vấn đề thời gian mà thôi.",
    "这件事你答应也好，不答应也罢，我都铁了心要去做。": "Chuyện này bạn có gật đầu đồng ý hay lắc đầu phản đối chăng nữa, tôi cũng đã sắt đá hạ quyết tâm làm cho bằng được.",
    "那些为迎合市场而推出的快餐读物，不看也罢。": "Mấy thứ ấn phẩm đọc nhanh mì ăn liền chỉ nhằm mưu toan chiều chuộng thị hiếu tầm thường kia, không đọc cũng chẳng tiếc.",
    "朋友在精不在多，人生得一知己足矣。": "Bạn bè quý ở sự chân tình chứ đâu cần số lượng, đời người chỉ cần tìm được một tri kỷ tâm giao thế là đủ mãn nguyện lắm rồi.",
    "作为一个摄影爱好者，我对这位国际知名的摄影大师仰慕久矣。": "Với tư cách là một người say mê nghệ thuật nhiếp ảnh, lòng tôi đã hướng về ngưỡng mộ vị đại sư danh tiếng lẫy lừng thế giới này từ thuở nào rồi vậy."
}
