-- Private administration and privacy-aware visitor analytics.
-- Apply this migration only after the intended administrator has registered the
-- username referenced in the final provisioning block. No password is stored here.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  singleton boolean not null default true unique,
  created_at timestamptz not null default pg_catalog.now(),
  constraint admin_users_singleton check (singleton)
);

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default pg_catalog.now(),
  ip_address inet,
  visitor_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  path text not null,
  referrer text,
  user_agent text,
  constraint visitor_events_path_length check (
    pg_catalog.char_length(path) between 1 and 500
  ),
  constraint visitor_events_referrer_length check (
    referrer is null or pg_catalog.char_length(referrer) <= 1000
  ),
  constraint visitor_events_user_agent_length check (
    user_agent is null or pg_catalog.char_length(user_agent) <= 1000
  )
);

create index if not exists visitor_events_visited_at_idx
  on public.visitor_events (visited_at desc);
create index if not exists visitor_events_ip_visited_idx
  on public.visitor_events (ip_address, visited_at desc);
create index if not exists visitor_events_visitor_visited_idx
  on public.visitor_events (visitor_id, visited_at desc);
create index if not exists visitor_events_user_visited_idx
  on public.visitor_events (user_id, visited_at desc);

alter table public.admin_users enable row level security;
alter table public.visitor_events enable row level security;

-- Both tables intentionally have no client-facing policies. Every read is made
-- through an admin-only security-definer function below.
revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.visitor_events from anon, authenticated;

create or replace function public.hanyu_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users a
    where a.user_id = (select auth.uid())
  );
$$;

create or replace function public.track_page_view(
  p_visitor_id uuid,
  p_path text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_headers jsonb := '{}'::jsonb;
  raw_ip text;
  parsed_ip inet;
  normalized_path text;
  request_referrer text;
  request_user_agent text;
  current_user_id uuid := (select auth.uid());
begin
  if p_visitor_id is null then return false; end if;

  normalized_path := pg_catalog.left(pg_catalog.btrim(coalesce(p_path, '')), 500);
  if normalized_path = '' or pg_catalog.left(normalized_path, 1) <> '/' then
    return false;
  end if;

  begin
    request_headers := coalesce(
      nullif(pg_catalog.current_setting('request.headers', true), '')::jsonb,
      '{}'::jsonb
    );
  exception when others then
    request_headers := '{}'::jsonb;
  end;

  raw_ip := pg_catalog.btrim(coalesce(
    request_headers ->> 'cf-connecting-ip',
    request_headers ->> 'x-real-ip',
    pg_catalog.split_part(request_headers ->> 'x-forwarded-for', ',', 1)
  ));

  if raw_ip <> '' then
    begin
      parsed_ip := raw_ip::inet;
    exception when invalid_text_representation then
      parsed_ip := null;
    end;
  end if;

  request_referrer := pg_catalog.left(
    nullif(pg_catalog.btrim(request_headers ->> 'referer'), ''),
    1000
  );
  request_user_agent := pg_catalog.left(
    nullif(pg_catalog.btrim(request_headers ->> 'user-agent'), ''),
    1000
  );

  -- Ignore duplicate SPA/dev-mode events and cap abusive clients.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_visitor_id::text || ':' || normalized_path, 0)
  );
  if exists (
    select 1 from public.visitor_events v
    where v.visitor_id = p_visitor_id
      and v.path = normalized_path
      and v.visited_at >= pg_catalog.now() - interval '30 seconds'
  ) then
    return false;
  end if;

  if parsed_ip is not null and (
    select pg_catalog.count(*) from public.visitor_events v
    where v.ip_address = parsed_ip
      and v.visited_at >= pg_catalog.now() - interval '1 hour'
  ) >= 300 then
    return false;
  elsif parsed_ip is null and (
    select pg_catalog.count(*) from public.visitor_events v
    where v.visitor_id = p_visitor_id
      and v.visited_at >= pg_catalog.now() - interval '1 hour'
  ) >= 300 then
    return false;
  end if;

  insert into public.visitor_events (
    ip_address, visitor_id, user_id, path, referrer, user_agent
  ) values (
    parsed_ip, p_visitor_id, current_user_id, normalized_path,
    request_referrer, request_user_agent
  );

  -- Lightweight opportunistic retention cleanup; no scheduler is required.
  if pg_catalog.random() < 0.02 then
    delete from public.visitor_events
    where visited_at < pg_catalog.now() - interval '90 days';
  end if;

  return true;
end;
$$;

create or replace function public.admin_get_summary()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  bangkok_day_start timestamptz := (
    pg_catalog.date_trunc('day', pg_catalog.now() at time zone 'Asia/Bangkok')
    at time zone 'Asia/Bangkok'
  );
  result jsonb;
begin
  if not public.hanyu_is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  select pg_catalog.jsonb_build_object(
    'visits_today', (select pg_catalog.count(*) from public.visitor_events v where v.visited_at >= bangkok_day_start),
    'visits_last_7_days', (select pg_catalog.count(*) from public.visitor_events v where v.visited_at >= bangkok_day_start - interval '6 days'),
    'unique_visitors_today', (select pg_catalog.count(distinct v.visitor_id) from public.visitor_events v where v.visited_at >= bangkok_day_start),
    'unique_ips_today', (select pg_catalog.count(distinct v.ip_address) from public.visitor_events v where v.visited_at >= bangkok_day_start and v.ip_address is not null),
    'anonymous_today', (select pg_catalog.count(*) from public.visitor_events v where v.visited_at >= bangkok_day_start and v.user_id is null),
    'authenticated_today', (select pg_catalog.count(*) from public.visitor_events v where v.visited_at >= bangkok_day_start and v.user_id is not null),
    'total_users', (select pg_catalog.count(*) from public.profiles),
    'total_feedback', (select pg_catalog.count(*) from public.feedback_messages)
  ) into result;

  return result;
end;
$$;

create or replace function public.admin_get_visits(
  p_kind text default 'all',
  p_search text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  visited_at timestamptz,
  ip_address text,
  visitor_id uuid,
  user_id uuid,
  display_name text,
  username text,
  path text,
  referrer text,
  user_agent text,
  is_authenticated boolean,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.hanyu_is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  if coalesce(p_kind, 'all') not in ('all', 'anonymous', 'authenticated') then
    raise exception 'Invalid visit kind' using errcode = '22023';
  end if;

  return query
  with filtered as (
    select
      v.visited_at,
      v.ip_address::text as ip_address,
      v.visitor_id,
      v.user_id,
      p.display_name,
      p.username,
      v.path,
      v.referrer,
      v.user_agent,
      (v.user_id is not null) as is_authenticated
    from public.visitor_events v
    left join public.profiles p on p.id = v.user_id
    where (p_kind = 'all'
      or (p_kind = 'anonymous' and v.user_id is null)
      or (p_kind = 'authenticated' and v.user_id is not null))
      and (
        p_search is null or pg_catalog.btrim(p_search) = ''
        or pg_catalog.strpos(pg_catalog.lower(v.path), pg_catalog.lower(pg_catalog.btrim(p_search))) > 0
        or pg_catalog.strpos(pg_catalog.lower(coalesce(v.ip_address::text, '')), pg_catalog.lower(pg_catalog.btrim(p_search))) > 0
        or pg_catalog.strpos(pg_catalog.lower(coalesce(p.username, '')), pg_catalog.lower(pg_catalog.btrim(p_search))) > 0
        or pg_catalog.strpos(v.visitor_id::text, pg_catalog.lower(pg_catalog.btrim(p_search))) > 0
      )
  )
  select f.*, pg_catalog.count(*) over () as total_count
  from filtered f
  order by f.visited_at desc
  limit least(100, greatest(1, coalesce(p_limit, 50)))
  offset greatest(0, coalesce(p_offset, 0));
end;
$$;

create or replace function public.admin_get_users(
  p_search text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  user_id uuid,
  username text,
  display_name text,
  avatar_url text,
  created_at timestamptz,
  xp integer,
  weekly_xp integer,
  completed integer,
  average_score integer,
  streak integer,
  hsk text,
  last_seen_at timestamptz,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.hanyu_is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  return query
  with filtered as (
    select
      p.id as user_id,
      p.username,
      p.display_name,
      p.avatar_url,
      p.created_at,
      (coalesce(s.xp, 0) + coalesce(public.hanyu_unified_xp(lp.progress), 0))::integer as xp,
      (coalesce(public.hanyu_progress_weekly_xp(lp.progress), 0) + coalesce(public.hanyu_unified_weekly_xp(lp.progress), 0))::integer as weekly_xp,
      coalesce(s.completed, 0)::integer as completed,
      coalesce(s.average_score, 0)::integer as average_score,
      coalesce(public.hanyu_progress_streak(lp.progress), 0)::integer as streak,
      coalesce(s.hsk, 'Mới học') as hsk,
      last_visit.last_seen_at
    from public.profiles p
    left join public.leaderboard_stats s on s.user_id = p.id
    left join public.learning_progress lp on lp.user_id = p.id
    left join lateral (
      select pg_catalog.max(v.visited_at) as last_seen_at
      from public.visitor_events v
      where v.user_id = p.id
    ) last_visit on true
    where p_search is null or pg_catalog.btrim(p_search) = ''
      or pg_catalog.strpos(pg_catalog.lower(p.username), pg_catalog.lower(pg_catalog.btrim(p_search))) > 0
      or pg_catalog.strpos(pg_catalog.lower(p.display_name), pg_catalog.lower(pg_catalog.btrim(p_search))) > 0
  )
  select f.*, pg_catalog.count(*) over () as total_count
  from filtered f
  order by f.created_at desc
  limit least(100, greatest(1, coalesce(p_limit, 50)))
  offset greatest(0, coalesce(p_offset, 0));
end;
$$;

create or replace function public.admin_get_feedback(
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  feedback_id uuid,
  user_id uuid,
  username text,
  display_name text,
  message text,
  created_at timestamptz,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.hanyu_is_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  return query
  select
    f.id as feedback_id,
    f.user_id,
    p.username,
    p.display_name,
    f.message,
    f.created_at,
    pg_catalog.count(*) over () as total_count
  from public.feedback_messages f
  left join public.profiles p on p.id = f.user_id
  order by f.created_at desc
  limit least(100, greatest(1, coalesce(p_limit, 50)))
  offset greatest(0, coalesce(p_offset, 0));
end;
$$;

revoke all on function public.hanyu_is_admin() from public;
revoke all on function public.track_page_view(uuid, text) from public;
revoke all on function public.admin_get_summary() from public;
revoke all on function public.admin_get_visits(text, text, integer, integer) from public;
revoke all on function public.admin_get_users(text, integer, integer) from public;
revoke all on function public.admin_get_feedback(integer, integer) from public;

grant execute on function public.hanyu_is_admin() to authenticated;
grant execute on function public.track_page_view(uuid, text) to anon, authenticated;
grant execute on function public.admin_get_summary() to authenticated;
grant execute on function public.admin_get_visits(text, text, integer, integer) to authenticated;
grant execute on function public.admin_get_users(text, integer, integer) to authenticated;
grant execute on function public.admin_get_feedback(integer, integer) to authenticated;

-- Secure one-time provisioning. This intentionally aborts if the intended account
-- does not exist yet, preventing a later registrant from claiming admin privileges.
do $$
declare
  intended_admin_id uuid;
begin
  select p.id into intended_admin_id
  from public.profiles p
  where p.username = 'mogiadev';

  if intended_admin_id is null then
    raise exception 'Register the intended admin account before applying this migration';
  end if;

  if exists (
    select 1 from public.admin_users a where a.user_id <> intended_admin_id
  ) then
    raise exception 'A different administrator is already provisioned';
  end if;

  insert into public.admin_users (user_id)
  values (intended_admin_id)
  on conflict (user_id) do nothing;
end;
$$;
